// CodeGear C++Builder
// Copyright (c) 1995, 2021 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Winapi.D3D11.pas' rev: 34.00 (Windows)

#ifndef Winapi_D3d11HPP
#define Winapi_D3d11HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <Winapi.DxgiFormat.hpp>
#include <Winapi.DxgiType.hpp>
#include <Winapi.DXGI.hpp>
#include <Winapi.D3DCommon.hpp>
#include <Winapi.Windows.hpp>
#include <System.Types.hpp>

//-- user supplied -----------------------------------------------------------
#include "D3D11.h"
#include "D3DCommon.h"
DECLARE_DINTERFACE_TYPE(ID3D11DeviceChild);
DECLARE_DINTERFACE_TYPE(ID3D11DepthStencilState);
DECLARE_DINTERFACE_TYPE(ID3D11BlendState);
DECLARE_DINTERFACE_TYPE(ID3D11RasterizerState);
DECLARE_DINTERFACE_TYPE(ID3D11Resource);
DECLARE_DINTERFACE_TYPE(ID3D11Buffer);
DECLARE_DINTERFACE_TYPE(ID3D11Texture1D);
DECLARE_DINTERFACE_TYPE(ID3D11Texture2D);
DECLARE_DINTERFACE_TYPE(ID3D11Texture3D);
DECLARE_DINTERFACE_TYPE(ID3D11View);
DECLARE_DINTERFACE_TYPE(ID3D11ShaderResourceView);
DECLARE_DINTERFACE_TYPE(ID3D11RenderTargetView);
DECLARE_DINTERFACE_TYPE(ID3D11DepthStencilView);
DECLARE_DINTERFACE_TYPE(ID3D11UnorderedAccessView);
DECLARE_DINTERFACE_TYPE(ID3D11VertexShader);
DECLARE_DINTERFACE_TYPE(ID3D11HullShader);
DECLARE_DINTERFACE_TYPE(ID3D11DomainShader);
DECLARE_DINTERFACE_TYPE(ID3D11GeometryShader);
DECLARE_DINTERFACE_TYPE(ID3D11PixelShader);
DECLARE_DINTERFACE_TYPE(ID3D11ComputeShader);
DECLARE_DINTERFACE_TYPE(ID3D11InputLayout);
DECLARE_DINTERFACE_TYPE(ID3D11SamplerState);
DECLARE_DINTERFACE_TYPE(ID3D11Asynchronous);
DECLARE_DINTERFACE_TYPE(ID3D11Query);
DECLARE_DINTERFACE_TYPE(ID3D11Predicate);
DECLARE_DINTERFACE_TYPE(ID3D11Counter);
DECLARE_DINTERFACE_TYPE(ID3D11ClassInstance);
DECLARE_DINTERFACE_TYPE(ID3D11ClassLinkage);
DECLARE_DINTERFACE_TYPE(ID3D11CommandList);
DECLARE_DINTERFACE_TYPE(ID3D11DeviceContext);
DECLARE_DINTERFACE_TYPE(ID3D11Device);

namespace Winapi
{
namespace D3d11
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
typedef unsigned TD3D11_BIND_FLAG;

typedef unsigned TD3D11_CPU_ACCESS_FLAG;

typedef unsigned TD3D11_CLEAR_FLAG;

typedef unsigned TD3D11_MAP;

typedef System::StaticArray<float, 4> TFourSingleArray;

typedef System::StaticArray<unsigned, 4> TFourUIntArray;

typedef _di_ID3D11VertexShader *PID3D11VertexShader;

typedef CD3D11_DEFAULT *PCD3D11_DEFAULT;

typedef D3D11_INPUT_CLASSIFICATION TD3D11_INPUT_CLASSIFICATION;

typedef D3D11_INPUT_ELEMENT_DESC TD3D11_INPUT_ELEMENT_DESC;

typedef D3D11_INPUT_ELEMENT_DESC *PD3D11_INPUT_ELEMENT_DESC;

typedef D3D11_FILL_MODE TD3D11_FILL_MODE;

typedef D3D11_CULL_MODE TD3D11_CULL_MODE;

typedef D3D11_SO_DECLARATION_ENTRY TD3D11_SO_DECLARATION_ENTRY;

typedef D3D11_SO_DECLARATION_ENTRY *PD3D11_SO_DECLARATION_ENTRY;

typedef D3D11_VIEWPORT TD3D11_VIEWPORT;

typedef D3D11_VIEWPORT *PD3D11_VIEWPORT;

typedef D3D11_RESOURCE_DIMENSION TD3D11_RESOURCE_DIMENSION;

typedef D3D11_DSV_DIMENSION TD3D11_DSV_DIMENSION;

typedef D3D11_RTV_DIMENSION TD3D11_RTV_DIMENSION;

typedef D3D11_UAV_DIMENSION TD3D11_UAV_DIMENSION;

typedef D3D11_USAGE TD3D11_USAGE;

typedef D3D11_RESOURCE_MISC_FLAG TD3D11_RESOURCE_MISC_FLAG;

typedef D3D11_MAP_FLAG TD3D11_MAP_FLAG;

typedef D3D11_RAISE_FLAG TD3D11_RAISE_FLAG;

typedef System::Types::TRect *PD3D11_RECT;

typedef D3D11_BOX TD3D11_BOX;

typedef D3D11_BOX *PD3D11_BOX;

typedef _di_ID3D11DeviceChild IID_ID3D11DeviceChild;

typedef D3D11_COMPARISON_FUNC TD3D11_COMPARISON_FUNC;

typedef D3D11_DEPTH_WRITE_MASK TD3D11_DEPTH_WRITE_MASK;

typedef D3D11_STENCIL_OP TD3D11_STENCIL_OP;

typedef D3D11_DEPTH_STENCILOP_DESC TD3D11_DEPTH_STENCILOP_DESC;

typedef D3D11_DEPTH_STENCILOP_DESC *PD3D11_DEPTH_STENCILOP_DESC;

typedef D3D11_DEPTH_STENCIL_DESC TD3D11_DEPTH_STENCIL_DESC;

typedef D3D11_DEPTH_STENCIL_DESC *PD3D11_DEPTH_STENCIL_DESC;

typedef D3D11_BLEND TD3D11_BLEND;

typedef D3D11_BLEND_OP TD3D11_BLEND_OP;

typedef D3D11_COLOR_WRITE_ENABLE TD3D11_COLOR_WRITE_ENABLE;

typedef D3D11_RENDER_TARGET_BLEND_DESC TD3D11_RENDER_TARGET_BLEND_DESC;

typedef D3D11_RENDER_TARGET_BLEND_DESC *PD3D11_RENDER_TARGET_BLEND_DESC;

typedef D3D11_BLEND_DESC TD3D11_BLEND_DESC;

typedef D3D11_BLEND_DESC *PD3D11_BLEND_DESC;

typedef D3D11_RASTERIZER_DESC TD3D11_RASTERIZER_DESC;

typedef D3D11_RASTERIZER_DESC *PD3D11_RASTERIZER_DESC;

typedef D3D11_SUBRESOURCE_DATA TD3D11_SUBRESOURCE_DATA;

typedef D3D11_SUBRESOURCE_DATA *PD3D11_SUBRESOURCE_DATA;

typedef D3D11_MAPPED_SUBRESOURCE TD3D11_MAPPED_SUBRESOURCE;

typedef D3D11_MAPPED_SUBRESOURCE *PD3D11_MAPPED_SUBRESOURCE;

typedef D3D11_BUFFER_DESC TD3D11_BUFFER_DESC;

typedef D3D11_BUFFER_DESC *PD3D11_BUFFER_DESC;

typedef D3D11_TEXTURE1D_DESC TD3D11_TEXTURE1D_DESC;

typedef D3D11_TEXTURE1D_DESC *PD3D11_TEXTURE1D_DESC;

typedef D3D11_TEXTURE2D_DESC TD3D11_TEXTURE2D_DESC;

typedef D3D11_TEXTURE2D_DESC *PD3D11_TEXTURE2D_DESC;

typedef D3D11_TEXTURE3D_DESC TD3D11_TEXTURE3D_DESC;

typedef D3D11_TEXTURE3D_DESC *PD3D11_TEXTURE3D_DESC;

typedef D3D11_TEXTURECUBE_FACE TD3D11_TEXTURECUBE_FACE;

typedef D3D11_BUFFER_SRV TD3D11_BUFFER_SRV;

typedef D3D11_BUFFER_SRV *PD3D11_BUFFER_SRV;

typedef D3D11_BUFFEREX_SRV_FLAG TD3D11_BUFFEREX_SRV_FLAG;

typedef D3D11_BUFFEREX_SRV TD3D11_BUFFEREX_SRV;

typedef D3D11_BUFFEREX_SRV *PD3D11_BUFFEREX_SRV;

typedef D3D11_TEX1D_SRV TD3D11_TEX1D_SRV;

typedef D3D11_TEX1D_SRV *PD3D11_TEX1D_SRV;

typedef D3D11_TEX1D_ARRAY_SRV TD3D11_TEX1D_ARRAY_SRV;

typedef D3D11_TEX1D_ARRAY_SRV *PD3D11_TEX1D_ARRAY_SRV;

typedef D3D11_TEX2D_SRV TD3D11_TEX2D_SRV;

typedef D3D11_TEX2D_SRV *PD3D11_TEX2D_SRV;

typedef D3D11_TEX2D_ARRAY_SRV TD3D11_TEX2D_ARRAY_SRV;

typedef D3D11_TEX2D_ARRAY_SRV *PD3D11_TEX2D_ARRAY_SRV;

typedef D3D11_TEX3D_SRV TD3D11_TEX3D_SRV;

typedef D3D11_TEX3D_SRV *PD3D11_TEX3D_SRV;

typedef D3D11_TEXCUBE_SRV TD3D11_TEXCUBE_SRV;

typedef D3D11_TEXCUBE_SRV *PD3D11_TEXCUBE_SRV;

typedef D3D11_TEXCUBE_ARRAY_SRV TD3D11_TEXCUBE_ARRAY_SRV;

typedef D3D11_TEXCUBE_ARRAY_SRV *PD3D11_TEXCUBE_ARRAY_SRV;

typedef D3D11_TEX2DMS_SRV TD3D11_TEX2DMS_SRV;

typedef D3D11_TEX2DMS_SRV *PD3D11_TEX2DMS_SRV;

typedef D3D11_TEX2DMS_ARRAY_SRV TD3D11_TEX2DMS_ARRAY_SRV;

typedef D3D11_TEX2DMS_ARRAY_SRV *PD3D11_TEX2DMS_ARRAY_SRV;

typedef D3D11_SHADER_RESOURCE_VIEW_DESC TD3D11_SHADER_RESOURCE_VIEW_DESC;

typedef D3D11_SHADER_RESOURCE_VIEW_DESC *PD3D11_SHADER_RESOURCE_VIEW_DESC;

typedef D3D11_BUFFER_RTV TD3D11_BUFFER_RTV;

typedef D3D11_BUFFER_RTV *PD3D11_BUFFER_RTV;

typedef D3D11_TEX1D_RTV TD3D11_TEX1D_RTV;

typedef D3D11_TEX1D_RTV *PD3D11_TEX1D_RTV;

typedef D3D11_TEX1D_ARRAY_RTV TD3D11_TEX1D_ARRAY_RTV;

typedef D3D11_TEX1D_ARRAY_RTV *PD3D11_TEX1D_ARRAY_RTV;

typedef D3D11_TEX2D_RTV TD3D11_TEX2D_RTV;

typedef D3D11_TEX2D_RTV *PD3D11_TEX2D_RTV;

typedef D3D11_TEX2DMS_RTV TD3D11_TEX2DMS_RTV;

typedef D3D11_TEX2DMS_RTV *PD3D11_TEX2DMS_RTV;

typedef D3D11_TEX2D_ARRAY_RTV TD3D11_TEX2D_ARRAY_RTV;

typedef D3D11_TEX2D_ARRAY_RTV *PD3D11_TEX2D_ARRAY_RTV;

typedef D3D11_TEX2DMS_ARRAY_RTV TD3D11_TEX2DMS_ARRAY_RTV;

typedef D3D11_TEX2DMS_ARRAY_RTV *PD3D11_TEX2DMS_ARRAY_RTV;

typedef D3D11_TEX3D_RTV TD3D11_TEX3D_RTV;

typedef D3D11_TEX3D_RTV *PD3D11_TEX3D_RTV;

typedef D3D11_RENDER_TARGET_VIEW_DESC TD3D11_RENDER_TARGET_VIEW_DESC;

typedef D3D11_RENDER_TARGET_VIEW_DESC *PD3D11_RENDER_TARGET_VIEW_DESC;

typedef D3D11_TEX1D_DSV TD3D11_TEX1D_DSV;

typedef D3D11_TEX1D_DSV *PD3D11_TEX1D_DSV;

typedef D3D11_TEX1D_ARRAY_DSV TD3D11_TEX1D_ARRAY_DSV;

typedef D3D11_TEX1D_ARRAY_DSV *PD3D11_TEX1D_ARRAY_DSV;

typedef D3D11_TEX2D_DSV TD3D11_TEX2D_DSV;

typedef D3D11_TEX2D_DSV *PD3D11_TEX2D_DSV;

typedef D3D11_TEX2D_ARRAY_DSV TD3D11_TEX2D_ARRAY_DSV;

typedef D3D11_TEX2D_ARRAY_DSV *PD3D11_TEX2D_ARRAY_DSV;

typedef D3D11_TEX2DMS_DSV TD3D11_TEX2DMS_DSV;

typedef D3D11_TEX2DMS_DSV *PD3D11_TEX2DMS_DSV;

typedef D3D11_TEX2DMS_ARRAY_DSV TD3D11_TEX2DMS_ARRAY_DSV;

typedef D3D11_TEX2DMS_ARRAY_DSV *PD3D11_TEX2DMS_ARRAY_DSV;

typedef D3D11_DSV_FLAG TD3D11_DSV_FLAG;

typedef D3D11_DSV_FLAG *PD3D11_DSV_FLAG;

typedef D3D11_DEPTH_STENCIL_VIEW_DESC TD3D11_DEPTH_STENCIL_VIEW_DESC;

typedef D3D11_DEPTH_STENCIL_VIEW_DESC *PD3D11_DEPTH_STENCIL_VIEW_DESC;

typedef D3D11_BUFFER_UAV_FLAG TD3D11_BUFFER_UAV_FLAG;

typedef D3D11_BUFFER_UAV TD3D11_BUFFER_UAV;

typedef D3D11_BUFFER_UAV *PD3D11_BUFFER_UAV;

typedef D3D11_TEX1D_UAV TD3D11_TEX1D_UAV;

typedef D3D11_TEX1D_UAV *PD3D11_TEX1D_UAV;

typedef D3D11_TEX1D_ARRAY_UAV TD3D11_TEX1D_ARRAY_UAV;

typedef D3D11_TEX1D_ARRAY_UAV *PD3D11_TEX1D_ARRAY_UAV;

typedef D3D11_TEX2D_UAV TD3D11_TEX2D_UAV;

typedef D3D11_TEX2D_UAV *PD3D11_TEX2D_UAV;

typedef D3D11_TEX2D_ARRAY_UAV TD3D11_TEX2D_ARRAY_UAV;

typedef D3D11_TEX2D_ARRAY_UAV *PD3D11_TEX2D_ARRAY_UAV;

typedef D3D11_TEX3D_UAV TD3D11_TEX3D_UAV;

typedef D3D11_TEX3D_UAV *PD3D11_TEX3D_UAV;

typedef D3D11_UNORDERED_ACCESS_VIEW_DESC TD3D11_UNORDERED_ACCESS_VIEW_DESC;

typedef D3D11_UNORDERED_ACCESS_VIEW_DESC *PD3D11_UNORDERED_ACCESS_VIEW_DESC;

typedef D3D11_FILTER TD3D11_FILTER;

typedef D3D11_FILTER_TYPE TD3D11_FILTER_TYPE;

typedef D3D11_TEXTURE_ADDRESS_MODE TD3D11_TEXTURE_ADDRESS_MODE;

typedef D3D11_SAMPLER_DESC TD3D11_SAMPLER_DESC;

typedef D3D11_SAMPLER_DESC *PD3D11_SAMPLER_DESC;

typedef D3D11_FORMAT_SUPPORT TD3D11_FORMAT_SUPPORT;

typedef D3D11_FORMAT_SUPPORT2 TD3D11_FORMAT_SUPPORT2;

typedef D3D11_ASYNC_GETDATA_FLAG TD3D11_ASYNC_GETDATA_FLAG;

typedef D3D11_QUERY TD3D11_QUERY;

typedef D3D11_QUERY_MISC_FLAG TD3D11_QUERY_MISC_FLAG;

typedef D3D11_QUERY_DESC TD3D11_QUERY_DESC;

typedef D3D11_QUERY_DESC *PD3D11_QUERY_DESC;

typedef D3D11_QUERY_DATA_TIMESTAMP_DISJOINT TD3D11_QUERY_DATA_TIMESTAMP_DISJOINT;

typedef D3D11_QUERY_DATA_TIMESTAMP_DISJOINT *PD3D11_QUERY_DATA_TIMESTAMP_DISJOINT;

typedef D3D11_QUERY_DATA_PIPELINE_STATISTICS TD3D11_QUERY_DATA_PIPELINE_STATISTICS;

typedef D3D11_QUERY_DATA_PIPELINE_STATISTICS *PD3D11_QUERY_DATA_PIPELINE_STATISTICS;

typedef D3D11_QUERY_DATA_SO_STATISTICS TD3D11_QUERY_DATA_SO_STATISTICS;

typedef D3D11_QUERY_DATA_SO_STATISTICS *PD3D11_QUERY_DATA_SO_STATISTICS;

typedef D3D11_COUNTER TD3D11_COUNTER;

typedef D3D11_COUNTER_TYPE TD3D11_COUNTER_TYPE;

typedef D3D11_COUNTER_DESC TD3D11_COUNTER_DESC;

typedef D3D11_COUNTER_DESC *PD3D11_COUNTER_DESC;

typedef D3D11_COUNTER_INFO TD3D11_COUNTER_INFO;

typedef D3D11_COUNTER_INFO *PD3D11_COUNTER_INFO;

typedef unsigned TD3D11_STANDARD_MULTISAMPLE_QUALITY_LEVELS;

typedef D3D11_DEVICE_CONTEXT_TYPE TD3D11_DEVICE_CONTEXT_TYPE;

typedef D3D11_CLASS_INSTANCE_DESC TD3D11_CLASS_INSTANCE_DESC;

typedef D3D11_CLASS_INSTANCE_DESC *PD3D11_CLASS_INSTANCE_DESC;

typedef D3D11_FEATURE TD3D11_FEATURE;

typedef D3D11_FEATURE_DATA_THREADING TD3D11_FEATURE_DATA_THREADING;

typedef D3D11_FEATURE_DATA_THREADING *PD3D11_FEATURE_DATA_THREADING;

typedef D3D11_FEATURE_DATA_DOUBLES TD3D11_FEATURE_DATA_DOUBLES;

typedef D3D11_FEATURE_DATA_DOUBLES *PD3D11_FEATURE_DATA_DOUBLES;

typedef D3D11_FEATURE_DATA_FORMAT_SUPPORT TD3D11_FEATURE_DATA_FORMAT_SUPPORT;

typedef D3D11_FEATURE_DATA_FORMAT_SUPPORT *PD3D11_FEATURE_DATA_FORMAT_SUPPORT;

typedef D3D11_FEATURE_DATA_FORMAT_SUPPORT2 TD3D11_FEATURE_DATA_FORMAT_SUPPORT2;

typedef D3D11_FEATURE_DATA_FORMAT_SUPPORT2 *PD3D11_FEATURE_DATA_FORMAT_SUPPORT2;

typedef D3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS TD3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS;

typedef D3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS *PD3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS;

typedef unsigned TD3D11_CREATE_DEVICE_FLAG;

//-- var, const, procedure ---------------------------------------------------
#define D3D11dll L"d3d11.dll"
extern "C" HRESULT __stdcall D3D11CreateDevice(_di_IDXGIAdapter pAdapter, D3D_DRIVER_TYPE DriverType, NativeUInt Software, unsigned Flags, const Winapi::D3dcommon::PD3D_FEATURE_LEVEL pFeatureLevels, unsigned FeatureLevels, unsigned SDKVersion, /* out */ _di_ID3D11Device &ppDevice, /* out */ unsigned &pFeatureLevel, /* out */ _di_ID3D11DeviceContext &ppImmediateContext);
extern "C" HRESULT __stdcall D3D11CreateDeviceAndSwapChain(_di_IDXGIAdapter pAdapter, D3D_DRIVER_TYPE DriverType, NativeUInt Software, unsigned Flags, const Winapi::D3dcommon::PD3D_FEATURE_LEVEL pFeatureLevels, unsigned FeatureLevels, unsigned SDKVersion, const Winapi::Dxgi::PDXGISwapChainDesc pSwapChainDesc, /* out */ _di_IDXGISwapChain &ppSwapChain, /* out */ _di_ID3D11Device &ppDevice, /* out */ unsigned &pFeatureLevel, /* out */ _di_ID3D11DeviceContext &ppImmediateContext);
extern DELPHI_PACKAGE HRESULT __fastcall MAKE_HRESULT(System::Word sev, System::Word fac, System::Word code);
extern DELPHI_PACKAGE HRESULT __fastcall MAKE_D3D11_HRESULT(System::Word code);
extern DELPHI_PACKAGE HRESULT __fastcall MAKE_D3D11_STATUS(System::Word code);
extern DELPHI_PACKAGE HRESULT __fastcall D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS(void);
extern DELPHI_PACKAGE HRESULT __fastcall D3D11_ERROR_FILE_NOT_FOUND(void);
extern DELPHI_PACKAGE HRESULT __fastcall D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS(void);
extern DELPHI_PACKAGE HRESULT __fastcall D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD(void);
extern DELPHI_PACKAGE System::LongBool __fastcall operator_equal(const D3D11_VIEWPORT &l, const D3D11_VIEWPORT &r);
extern DELPHI_PACKAGE System::LongBool __fastcall operator_notEqual(const D3D11_VIEWPORT &l, const D3D11_VIEWPORT &r);
extern DELPHI_PACKAGE unsigned __fastcall D3D11CalcSubresource(unsigned MipSlice, unsigned ArraySlice, unsigned MipLevels);
extern DELPHI_PACKAGE D3D11_FILTER __fastcall D3D11_ENCODE_BASIC_FILTER(unsigned min, unsigned mag, unsigned mip, unsigned bComparison);
extern DELPHI_PACKAGE D3D11_FILTER __fastcall D3D11_ENCODE_ANISOTROPIC_FILTER(unsigned bComparison);
extern DELPHI_PACKAGE D3D11_FILTER_TYPE __fastcall D3D11_DECODE_MIN_FILTER(unsigned d3d11Filter);
extern DELPHI_PACKAGE D3D11_FILTER_TYPE __fastcall D3D11_DECODE_MAG_FILTER(unsigned d3d11Filter);
extern DELPHI_PACKAGE D3D11_FILTER_TYPE __fastcall D3D11_DECODE_MIP_FILTER(unsigned d3d11Filter);
extern DELPHI_PACKAGE bool __fastcall D3D11_DECODE_IS_COMPARISON_FILTER(unsigned d3d11Filter);
extern DELPHI_PACKAGE bool __fastcall D3D11_DECODE_IS_ANISOTROPIC_FILTER(unsigned d3d11Filter);
extern DELPHI_PACKAGE void __fastcall D3D_SET_OBJECT_NAME_N_A(_di_ID3D11DeviceChild pObject, unsigned Chars, void * pName);
extern DELPHI_PACKAGE void __fastcall D3D_SET_OBJECT_NAME_A(_di_ID3D11DeviceChild pObject, void * pName);
}	/* namespace D3d11 */
}	/* namespace Winapi */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_WINAPI_D3D11)
using namespace Winapi::D3d11;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_WINAPI)
using namespace Winapi;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Winapi_D3d11HPP
