void CreateToolBar()
{
    TBBUTTON ToolBtn[]= {
        {0,IDM_FILE_NEW,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,0},
        {1,IDM_FILE_OPEN,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,1},
        {2,IDM_FILE_SAVE,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,2},
        {4,0,0,TBSTYLE_SEP,0,0},
        {3,IDM_EDIT_CUT,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,3},
        {4,IDM_EDIT_COPY,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,4},
        {5,IDM_EDIT_PASTE,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,5},
        {4,0,0,TBSTYLE_SEP,0,0},
        {6,IDM_SHAPE_SELECT,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,6},
        {7,IDM_SHAPE_LINE,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,7},
        {8,IDM_SHAPE_ELLIPSE,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,8},
        {9,IDM_SHAPE_RECTANGLE,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,9},
        {10,IDM_SHAPE_TEXT,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,10},
        {11,IDM_SHAPE_BITMAP,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,11},
        {12,IDM_SHAPE_META,TBSTATE_ENABLED,TBSTYLE_CHECKGROUP,0,0,0,12},
        {4,0,0,TBSTYLE_SEP,0,0},
        {13,IDM_SHAPE_PROPERTY,TBSTATE_ENABLED,TBSTYLE_BUTTON,0,0,0,13},
    };
    TCHAR *szToolText="새파일\0열기\0저장\0자르기\0복사\0붙이기"
                      "\0선택\0선\0원\0사각형\0텍스트\0비트맵\0메타\0속성\0";

    hToolBar=CreateToolbarEx(hWndMain, WS_CHILD | WS_VISIBLE
                             | TBSTYLE_TOOLTIPS | TBSTYLE_FLAT ,
                             99, 14, g_hInst, IDB_TOOLBAR, ToolBtn, 17,
                             16,15,16,15,sizeof(TBBUTTON));

    SendMessage(hToolBar,TB_ADDSTRING,NULL,(LPARAM)szToolText);
    SendMessage(hToolBar,TB_AUTOSIZE,0,0);
}