int
main ()
{
	float S[8][16], val;
	int i,k, count = 0;
	int vali;

	printf("/* sbc_coeffs.h - Automatically generated by cosdata.c. */\n\n");

	vali = SI_MULTI;
	printf("#define SIMULTI\t%d\n\n", vali);

	printf("static const int32_t sbc_coeffs8[] = {\n    ");
	for (k = 0;k < AC(sbc8_coeffs);k++) {
		if (count % 8 == 0 && count != 0)
			printf("\n    ");
		val = sbc8_coeffs[k] * COEFFS_MULTI;
		vali = roundf(val);
		printf("%d, ",vali);
		count++;
	}
	printf("\n};\n");

	count = 0;
	printf("static const int32_t sbc_coeffs4[] = {\n    ");
	for (k = 0;k < AC(sbc4_coeffs);k++) {
		if (count % 8 == 0 && count != 0)
			printf("\n    ");
		val = sbc4_coeffs[k] * COEFFS_MULTI;
		vali = roundf(val);
		printf("%d, ",vali);
		count++;
	}
	printf("\n};\n");

	count = 0;
	printf("static const int32_t cosdata8[8][16] = {\n    ");
	for (i = 0; i < 8; i++) {
		for (k = 0;k < 16;k++) {
			S[i][k] = cosf((i+0.5)*(k-4)*(M_PI_4/2));

			if (count % 8 == 0 && count != 0)
				printf("\n    ");
			if (k == 0)
				printf("{ ");
			val = S[i][k] * SI_MULTI;
			vali = roundf(val);
			printf("%d, ",vali);

			if (k == 15)
				printf("},");
			count++;
		}
	}
	printf("\n};\n");

	count = 0;
	printf("static const int32_t cosdata4[4][8] = {\n    ");
	for (i = 0; i < 4; i++) {
		for (k = 0;k < 8;k++) {
			S[i][k] = cosf((i+0.5)*(k-2)*(M_PI_4));

			if (count % 8 == 0 && count != 0)
				printf("\n    ");
			if (k == 0)
				printf("{ ");

			val = S[i][k] * SI_MULTI;
			vali = roundf(val);
			printf("%d, ",vali);

			if (k == 7)
				printf("},");
			count++;
		}
	}
	printf("\n};\n");

	return 0;
}