void DarkSusy_mH_125_mGammaD_2000_cT_10_LHE_Higgs_m()
{
//=========Macro generated from canvas: cnv/cnv
//=========  (Sun May 24 15:17:47 2015) by ROOT version6.02/05
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(1.784236,-0.24375,2.499296,1.63125);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetLogx();
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_higgs_M_dummy9 = new TH1F("h_higgs_M_dummy9","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy9->SetMaximum(1.5);
   h_higgs_M_dummy9->SetLineStyle(0);
   h_higgs_M_dummy9->SetMarkerStyle(20);
   h_higgs_M_dummy9->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy9->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy9->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy9->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy9->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy9->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy9->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy9->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy9->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy9->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy9->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy9->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy9->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy9->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy9->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy9->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy9->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy9->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy9->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy9->Draw("");
   
   TH1F *h_higgs_M_dummy10 = new TH1F("h_higgs_M_dummy10","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy10->SetMaximum(1.5);
   h_higgs_M_dummy10->SetLineStyle(0);
   h_higgs_M_dummy10->SetMarkerStyle(20);
   h_higgs_M_dummy10->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy10->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy10->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy10->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy10->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy10->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy10->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy10->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy10->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy10->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy10->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy10->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy10->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy10->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy10->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy10->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy10->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy10->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy10->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy10->Draw("same");
   
   TH1F *h_higgs_M11 = new TH1F("h_higgs_M11","h_higgs_M",10,120.5,130.5);
   h_higgs_M11->SetBinContent(5,1);
   h_higgs_M11->SetBinError(5,0.003535556);
   h_higgs_M11->SetEntries(79999);
   h_higgs_M11->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   h_higgs_M11->SetLineColor(ci);
   h_higgs_M11->SetLineWidth(2);
   h_higgs_M11->SetMarkerStyle(20);
   h_higgs_M11->GetXaxis()->SetLabelFont(42);
   h_higgs_M11->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M11->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M11->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M11->GetXaxis()->SetTitleFont(42);
   h_higgs_M11->GetYaxis()->SetLabelFont(42);
   h_higgs_M11->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M11->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M11->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M11->GetYaxis()->SetTitleFont(42);
   h_higgs_M11->GetZaxis()->SetLabelFont(42);
   h_higgs_M11->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M11->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M11->GetZaxis()->SetTitleFont(42);
   h_higgs_M11->Draw("SAMEHIST");
   
   TH1F *h_higgs_M12 = new TH1F("h_higgs_M12","h_higgs_M",10,120.5,130.5);
   h_higgs_M12->SetBinContent(5,1);
   h_higgs_M12->SetBinError(5,0.003535556);
   h_higgs_M12->SetEntries(79999);
   h_higgs_M12->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   h_higgs_M12->SetLineColor(ci);
   h_higgs_M12->SetLineWidth(2);
   h_higgs_M12->SetMarkerStyle(20);
   h_higgs_M12->GetXaxis()->SetMoreLogLabels();
   h_higgs_M12->GetXaxis()->SetLabelFont(42);
   h_higgs_M12->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M12->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M12->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M12->GetXaxis()->SetTitleFont(42);
   h_higgs_M12->GetYaxis()->SetLabelFont(42);
   h_higgs_M12->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M12->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M12->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M12->GetYaxis()->SetTitleFont(42);
   h_higgs_M12->GetZaxis()->SetLabelFont(42);
   h_higgs_M12->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M12->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M12->GetZaxis()->SetTitleFont(42);
   h_higgs_M12->Draw("SAMEHIST");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 50 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 20 GeV, c#tau_{#gamma_{D}} = 10 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14 TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1F *h_higgs_M_dummy13 = new TH1F("h_higgs_M_dummy13","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy13->SetMaximum(1.5);
   h_higgs_M_dummy13->SetLineStyle(0);
   h_higgs_M_dummy13->SetMarkerStyle(20);
   h_higgs_M_dummy13->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy13->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy13->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy13->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy13->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy13->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy13->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy13->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy13->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy13->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy13->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy13->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy13->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy13->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy13->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy13->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy13->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy13->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy13->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy13->Draw("same");
   
   TH1F *h_higgs_M14 = new TH1F("h_higgs_M14","h_higgs_M",10,120.5,130.5);
   h_higgs_M14->SetBinContent(5,1);
   h_higgs_M14->SetBinError(5,0.003535556);
   h_higgs_M14->SetEntries(79999);
   h_higgs_M14->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   h_higgs_M14->SetLineColor(ci);
   h_higgs_M14->SetLineWidth(2);
   h_higgs_M14->SetMarkerStyle(20);
   h_higgs_M14->GetXaxis()->SetMoreLogLabels();
   h_higgs_M14->GetXaxis()->SetLabelFont(42);
   h_higgs_M14->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M14->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M14->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M14->GetXaxis()->SetTitleFont(42);
   h_higgs_M14->GetYaxis()->SetLabelFont(42);
   h_higgs_M14->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M14->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M14->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M14->GetYaxis()->SetTitleFont(42);
   h_higgs_M14->GetZaxis()->SetLabelFont(42);
   h_higgs_M14->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M14->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M14->GetZaxis()->SetTitleFont(42);
   h_higgs_M14->Draw("SAMEHIST");
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}