int main(int argc, char *argv[])
{
	char buffer[BUFSIZ];
	unsigned long startch;
	unsigned long ch;
	char *ptr;
	char *catName;
	unsigned long upperch;
	unsigned long lowerch;
	unsigned long titlech;

	/* Initialize the value tables to straight-through mappings */
	for(ch = 0; ch < 65536; ++ch)
	{
		lower[ch] = (unsigned short)ch;
		upper[ch] = (unsigned short)ch;
		title[ch] = (unsigned short)ch;
	}

	/* Process UnicodeData.txt to get the case conversion information */
	startch = 0;
	while(fgets(buffer, sizeof(buffer), stdin))
	{
		ptr = buffer;

		/* Parse the character value */
		ch = parseHex(&ptr, 0);
		if(*ptr != ';')
		{
			continue;
		}

		/* Skip the character if not within the 16-bit range */
		if(ch >= 0x10000)
		{
			startch = ch + 1;
			continue;
		}

		/* Find the category name */
		++ptr;
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		catName = ptr;
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}

		/* If the character name ended in ", Last>", then ignore
		   the character range */
		if((catName - buffer) > 8 && !strncmp(catName - 8, ", Last>", 7))
		{
			continue;
		}

		/* Find the case conversion fields */
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}
		while(*ptr != '\0' && *ptr != ';')
		{
			++ptr;
		}
		if(*ptr == ';')
		{
			++ptr;
		}

		/* Extract the upper, lower, and title mappings */
		upperch = parseHex(&ptr, ch);
		if(*ptr != ';')
		{
			continue;
		}
		++ptr;
		lowerch = parseHex(&ptr, ch);
		if(*ptr != ';')
		{
			continue;
		}
		++ptr;
		titlech = parseHex(&ptr, ch);

		/* Update the case mapping tables */
		upper[ch] = (unsigned short)upperch;
		lower[ch] = (unsigned short)lowerch;
		title[ch] = (unsigned short)titlech;
	}

	/* Write out the mapping tables */
	printf("/* This file is automatically generated - do not edit */\n");
	printf("#define	UNICASE_RANGE1_LOWER  0x%04X\n", RANGE1_LOWER);
	printf("#define	UNICASE_RANGE1_UPPER  0x%04X\n", RANGE1_UPPER);
	printf("#define	UNICASE_RANGE1_OFFSET 0x%04X\n", 0);
	printf("#define	UNICASE_RANGE2_LOWER  0x%04X\n", RANGE2_LOWER);
	printf("#define	UNICASE_RANGE2_UPPER  0x%04X\n", RANGE2_UPPER);
	printf("#define	UNICASE_RANGE2_OFFSET 0x%04X\n", RANGE1_UPPER + 1);
	printf("#define	UNICASE_RANGE3_LOWER  0x%04X\n", RANGE3_LOWER);
	printf("#define	UNICASE_RANGE3_UPPER  0x%04X\n", RANGE3_UPPER);
	printf("#define	UNICASE_RANGE3_OFFSET 0x%04X\n",
		   (RANGE1_UPPER - RANGE1_LOWER + 1) +
		   (RANGE2_UPPER - RANGE2_LOWER + 1));
	writeTable("unicodeToUpper", upper);
	writeTable("unicodeToLower", lower);
#if 0
	writeTable("unicodeToTitle", title);
#endif

	/* Done */
	return 0;
}