KARROT_EXPORT int k_driver_init(KDriver *driver)
{
	DWORD msg_filter
		= INSTALLLOGMODE_PROGRESS
		| INSTALLLOGMODE_FATALEXIT
		| INSTALLLOGMODE_ERROR
		| INSTALLLOGMODE_WARNING
		| INSTALLLOGMODE_USER
		| INSTALLLOGMODE_INFO
		| INSTALLLOGMODE_RESOLVESOURCE
		| INSTALLLOGMODE_OUTOFDISKSPACE
		| INSTALLLOGMODE_ACTIONSTART
		| INSTALLLOGMODE_ACTIONDATA
		| INSTALLLOGMODE_COMMONDATA
		| INSTALLLOGMODE_PROGRESS
		| INSTALLLOGMODE_INITIALIZE
		| INSTALLLOGMODE_TERMINATE
		| INSTALLLOGMODE_SHOWDIALOG
		;

	MsiSetExternalUI(install_ui, msg_filter, NULL);
	MsiSetInternalUI(INSTALLUILEVEL_NONE | INSTALLUILEVEL_SOURCERESONLY, NULL);

	driver->fields = fields;
	driver->handle = handle;
	driver->finalize = finalize;
	driver->get_error_message = get_error_message;
	driver->ctx = subversion;

	return 0;
}