void ParaEngine::CParaWorldAsset::SaveAssetFileMapping()
{
#ifdef USE_DIRECTX_RENDERER
	if (m_bUseAssetSearch)
	{
		CParaFile file;
		if (file.OpenFile(ASSET_MAP_FILEPATH, false))
		{
			file.SetFilePointer(0, FILE_BEGIN);
			file.SetEndOfFile();
			file.SetFilePointer(0, FILE_BEGIN);
			file.WriteString("-- automatically generated by ParaEngine Asset manager.\r\n");
			map<string, string>::const_iterator itCur, itEnd = m_AssetMap.end();

			for (itCur = m_AssetMap.begin(); itCur != itEnd; ++itCur)
			{
				file.WriteFormated("%s=%s\r\n", (itCur->first).c_str(), (itCur->second).c_str());
			}
		}
	}
#endif
}