// Construct from components
Foam::thoboisSlidingValve::thoboisSlidingValve
(
    const word& name,
    const polyMesh& mesh,
    const autoPtr<coordinateSystem>& valveCS,
    const word& bottomPatchName,
    const word& poppetPatchName,
    const word& sidePatchName,
    const word& stemPatchName,
    const word& curtainInPortPatchName,
    const word& curtainInCylinderPatchName,
    const word& detachInCylinderPatchName,
    const word& detachInPortPatchName,
    const labelList& detachFaces,
    const graph& liftProfile,
    const scalar minLift,
    const scalar diameter,
    const scalar deformationLift,
    const word& layeringFacesTopName,
    const word& layeringFacesBottomName,
    const word& movingCellsTopName,
    const word& movingCellsBottomName,
    const word& movingPointsTopName,
    const word& movingPointsBottomName,
    const scalar minTopLayer,
    const scalar maxTopLayer,
    const scalar minBottomLayer,
    const scalar maxBottomLayer,
    const word& staticPointsName,
    const word& movingPointsName,
    const word& staticCellsName,
    const word& movingCellsName
)
:
    name_(name),
    mesh_(mesh),
    engineDB_(refCast<const engineTime>(mesh.time())),
    csPtr_(valveCS),
    bottomPatch_(bottomPatchName, mesh.boundaryMesh()),
    poppetPatch_(poppetPatchName, mesh.boundaryMesh()),
    sidePatch_(sidePatchName, mesh.boundaryMesh()),
    stemPatch_(stemPatchName, mesh.boundaryMesh()),
    curtainInCylinderPatch_(curtainInPortPatchName, mesh.boundaryMesh()),
    curtainInPortPatch_(curtainInPortPatchName, mesh.boundaryMesh()),
    detachInCylinderPatch_(detachInCylinderPatchName, mesh.boundaryMesh()),
    detachInPortPatch_(detachInPortPatchName, mesh.boundaryMesh()),
    detachFaces_(detachFaces),
    liftProfile_(liftProfile),
    liftProfileStart_(min(liftProfile_.x())),
    liftProfileEnd_(max(liftProfile_.x())),
    minLift_(minLift),
    diameter_(diameter),
    deformationLift_(deformationLift),
    layeringFacesTopName_(layeringFacesTopName),
    layeringFacesBottomName_(layeringFacesBottomName),
    movingCellsTopName_(movingCellsTopName),
    movingCellsBottomName_(movingCellsBottomName),
    movingPointsTopName_(movingPointsTopName),
    movingPointsBottomName_(movingPointsBottomName),
    minTopLayer_(minTopLayer),
    maxTopLayer_(maxTopLayer),
    minBottomLayer_(minBottomLayer),
    maxBottomLayer_(maxBottomLayer),
    staticPointsName_(staticPointsName),
    movingPointsName_(movingPointsName),
    staticCellsName_(staticCellsName),
    movingCellsName_(movingCellsName)
{}