// CodeGear C++Builder
// Copyright (c) 1995, 2021 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'iOSapi.OpenGLES.pas' rev: 34.00 (iOS)

#ifndef Iosapi_OpenglesHPP
#define Iosapi_OpenglesHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <Macapi.ObjCRuntime.hpp>
#include <Macapi.ObjectiveC.hpp>
#include <iOSapi.Foundation.hpp>
#include <iOSapi.CocoaTypes.hpp>
#include <System.Rtti.hpp>

//-- user supplied -----------------------------------------------------------

namespace Iosapi
{
namespace Opengles
{
//-- forward type declarations -----------------------------------------------
__interface DELPHIINTERFACE EAGLDrawable;
typedef System::DelphiInterface<EAGLDrawable> _di_EAGLDrawable;
__interface DELPHIINTERFACE EAGLContextClass;
typedef System::DelphiInterface<EAGLContextClass> _di_EAGLContextClass;
__interface DELPHIINTERFACE EAGLContext;
typedef System::DelphiInterface<EAGLContext> _di_EAGLContext;
class DELPHICLASS TEAGLContext;
//-- type declarations -------------------------------------------------------
typedef unsigned long EAGLRenderingAPI;

typedef Iosapi::Foundation::_di_NSObject EAGLSharegroup;

typedef unsigned GLbitfield;

typedef System::Byte GLboolean;

typedef System::Byte *PGLboolean;

typedef System::Int8 GLbyte;

typedef System::Int8 *PGLbyte;

typedef double GLcampd;

typedef System::Byte GLchar;

typedef char * PGLchar;

typedef char * PGLcharARB;

typedef double GLclampd;

typedef float GLclampf;

typedef float *PGLclampf;

typedef int GLclampx;

typedef double GLdouble;

typedef double *PGLdouble;

typedef unsigned GLenum;

typedef unsigned *PGLenum;

typedef int GLfixed;

typedef int *PGLfixed;

typedef float GLfloat;

typedef float *PGLfloat;

typedef unsigned long GLhandleARB;

typedef unsigned long *PGLhandleARB;

typedef int GLint;

typedef NativeInt GLintptr;

typedef NativeInt GLintptrARB;

typedef int *PGLint;

typedef short GLshort;

typedef short *PGLshort;

typedef int GLsizei;

typedef NativeInt GLsizeiptr;

typedef NativeInt GLsizeiptrARB;

typedef int *PGLsizei;

typedef System::Byte GLubyte;

typedef System::Byte *PGLubyte;

typedef unsigned GLuint;

typedef unsigned *PGLuint;

typedef System::Word GLushort;

typedef System::Word *PGLushort;

typedef System::PWord PUnsigned;

typedef void * GLvoid;

typedef void * PGLvoid;

typedef void * Pvoid;

__interface  INTERFACE_UUID("{6210BEF7-9C9F-4EED-AF96-4630097E8126}") EAGLDrawable  : public System::IInterface 
{
	virtual Iosapi::Foundation::_di_NSDictionary __cdecl drawableProperties() = 0 ;
	virtual void __cdecl setDrawableProperties(Iosapi::Foundation::_di_NSDictionary drawableProperties) = 0 ;
};

__interface  INTERFACE_UUID("{323D4256-6B45-4D72-A8AF-F33A16682537}") EAGLContextClass  : public Iosapi::Foundation::NSObjectClass 
{
	virtual void * __cdecl currentContext() = 0 ;
	virtual bool __cdecl setCurrentContext(_di_EAGLContext context) = 0 ;
};

__interface  INTERFACE_UUID("{880F106B-5A66-475F-8EBC-6F57A4378154}") EAGLContext  : public Iosapi::Foundation::NSObject 
{
	virtual unsigned long __cdecl API() = 0 ;
	virtual void * __cdecl initWithAPI(unsigned long api) = 0 /* overload */;
	virtual void * __cdecl initWithAPI(unsigned long api, Iosapi::Foundation::_di_NSObject sharegroup) = 0 /* overload */;
	virtual bool __cdecl presentRenderbuffer(unsigned long target) = 0 ;
	virtual bool __cdecl renderbufferStorage(unsigned long target, void * fromDrawable) = 0 ;
	virtual Iosapi::Foundation::_di_NSObject __cdecl sharegroup() = 0 ;
};

class PASCALIMPLEMENTATION TEAGLContext : public Macapi::Objectivec::TOCGenericImport__2<_di_EAGLContextClass,_di_EAGLContext>
{
	typedef Macapi::Objectivec::TOCGenericImport__2<_di_EAGLContextClass,_di_EAGLContext> inherited;
	
public:
	/* TOCImport.Create */ inline __fastcall TEAGLContext(void * ID, void * ClsID, Macapi::Objectivec::TOCVTable* VTable) : Macapi::Objectivec::TOCGenericImport__2<_di_EAGLContextClass,_di_EAGLContext>(ID, ClsID, VTable) { }
	/* TOCImport.Destroy */ inline __fastcall virtual ~TEAGLContext() { }
	
};


//-- var, const, procedure ---------------------------------------------------
static constexpr System::Int8 EAGL_MAJOR_VERSION = System::Int8(0x1);
static constexpr System::Int8 EAGL_MINOR_VERSION = System::Int8(0x0);
static constexpr System::Word GL_ACTIVE_ATTRIBUTES = System::Word(0x8b89);
static constexpr System::Word GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = System::Word(0x8b8a);
static constexpr System::Word GL_ACTIVE_PROGRAM_EXT = System::Word(0x8259);
static constexpr System::Word GL_ACTIVE_TEXTURE = System::Word(0x84e0);
static constexpr System::Word GL_ACTIVE_UNIFORMS = System::Word(0x8b86);
static constexpr System::Word GL_ACTIVE_UNIFORM_MAX_LENGTH = System::Word(0x8b87);
static constexpr System::Word GL_ADD = System::Word(0x104);
static constexpr System::Word GL_ADD_SIGNED = System::Word(0x8574);
static constexpr System::Word GL_ALIASED_LINE_WIDTH_RANGE = System::Word(0x846e);
static constexpr System::Word GL_ALIASED_POINT_SIZE_RANGE = System::Word(0x846d);
static constexpr unsigned GL_ALL_SHADER_BITS_EXT = unsigned(0xffffffff);
static constexpr System::Word GL_ALPHA = System::Word(0x1906);
static constexpr System::Word GL_ALPHA_BITS = System::Word(0xd55);
static constexpr System::Word GL_ALPHA_SCALE = System::Word(0xd1c);
static constexpr System::Word GL_ALPHA_TEST = System::Word(0xbc0);
static constexpr System::Word GL_ALPHA_TEST_FUNC = System::Word(0xbc1);
static constexpr System::Word GL_ALPHA_TEST_REF = System::Word(0xbc2);
static constexpr System::Word GL_ALWAYS = System::Word(0x207);
static constexpr System::Word GL_AMBIENT = System::Word(0x1200);
static constexpr System::Word GL_AMBIENT_AND_DIFFUSE = System::Word(0x1602);
static constexpr System::Word GL_AND = System::Word(0x1501);
static constexpr System::Word GL_AND_INVERTED = System::Word(0x1504);
static constexpr System::Word GL_AND_REVERSE = System::Word(0x1502);
static constexpr System::Word GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT = System::Word(0x8d6a);
static constexpr System::Word GL_ANY_SAMPLES_PASSED_EXT = System::Word(0x8c2f);
static constexpr System::Int8 GL_APPLE_framebuffer_multisample = System::Int8(0x1);
static constexpr System::Int8 GL_APPLE_rgb_422 = System::Int8(0x1);
static constexpr System::Int8 GL_APPLE_texture_2D_limited_npot = System::Int8(0x1);
static constexpr System::Int8 GL_APPLE_texture_format_BGRA8888 = System::Int8(0x1);
static constexpr System::Int8 GL_APPLE_texture_max_level = System::Int8(0x1);
static constexpr System::Word GL_ARRAY_BUFFER = System::Word(0x8892);
static constexpr System::Word GL_ARRAY_BUFFER_BINDING = System::Word(0x8894);
static constexpr System::Word GL_ATTACHED_SHADERS = System::Word(0x8b85);
static constexpr System::Word GL_BACK = System::Word(0x405);
static constexpr System::Word GL_BGRA = System::Word(0x80e1);
static constexpr System::Word GL_BGRA_EXT = System::Word(0x80e1);
static constexpr System::Word GL_BGRA_IMG = System::Word(0x80e1);
static constexpr System::Word GL_BLEND = System::Word(0xbe2);
static constexpr System::Word GL_BLEND_COLOR = System::Word(0x8005);
static constexpr System::Word GL_BLEND_DST = System::Word(0xbe0);
static constexpr System::Word GL_BLEND_DST_ALPHA = System::Word(0x80ca);
static constexpr System::Word GL_BLEND_DST_ALPHA_OES = System::Word(0x80ca);
static constexpr System::Word GL_BLEND_DST_RGB = System::Word(0x80c8);
static constexpr System::Word GL_BLEND_DST_RGB_OES = System::Word(0x80c8);
static constexpr System::Word GL_BLEND_EQUATION = System::Word(0x8009);
static constexpr System::Word GL_BLEND_EQUATION_ALPHA = System::Word(0x883d);
static constexpr System::Word GL_BLEND_EQUATION_ALPHA_OES = System::Word(0x883d);
static constexpr System::Word GL_BLEND_EQUATION_OES = System::Word(0x8009);
static constexpr System::Word GL_BLEND_EQUATION_RGB = System::Word(0x8009);
static constexpr System::Word GL_BLEND_EQUATION_RGB_OES = System::Word(0x8009);
static constexpr System::Word GL_BLEND_SRC = System::Word(0xbe1);
static constexpr System::Word GL_BLEND_SRC_ALPHA = System::Word(0x80cb);
static constexpr System::Word GL_BLEND_SRC_ALPHA_OES = System::Word(0x80cb);
static constexpr System::Word GL_BLEND_SRC_RGB = System::Word(0x80c9);
static constexpr System::Word GL_BLEND_SRC_RGB_OES = System::Word(0x80c9);
static constexpr System::Word GL_BLUE_BITS = System::Word(0xd54);
static constexpr System::Word GL_BOOL = System::Word(0x8b56);
static constexpr System::Word GL_BOOL_VEC2 = System::Word(0x8b57);
static constexpr System::Word GL_BOOL_VEC3 = System::Word(0x8b58);
static constexpr System::Word GL_BOOL_VEC4 = System::Word(0x8b59);
static constexpr System::Word GL_BUFFER_ACCESS_OES = System::Word(0x88bb);
static constexpr System::Word GL_BUFFER_MAPPED_OES = System::Word(0x88bc);
static constexpr System::Word GL_BUFFER_MAP_POINTER_OES = System::Word(0x88bd);
static constexpr System::Word GL_BUFFER_OBJECT_EXT = System::Word(0x9151);
static constexpr System::Word GL_BUFFER_SIZE = System::Word(0x8764);
static constexpr System::Word GL_BUFFER_USAGE = System::Word(0x8765);
static constexpr System::Word GL_BYTE = System::Word(0x1400);
static constexpr System::Word GL_CCW = System::Word(0x901);
static constexpr System::Word GL_CLAMP_TO_EDGE = System::Word(0x812f);
static constexpr System::Word GL_CLEAR = System::Word(0x1500);
static constexpr System::Word GL_CLIENT_ACTIVE_TEXTURE = System::Word(0x84e1);
static constexpr System::Word GL_CLIP_PLANE0 = System::Word(0x3000);
static constexpr System::Word GL_CLIP_PLANE1 = System::Word(0x3001);
static constexpr System::Word GL_CLIP_PLANE2 = System::Word(0x3002);
static constexpr System::Word GL_CLIP_PLANE3 = System::Word(0x3003);
static constexpr System::Word GL_CLIP_PLANE4 = System::Word(0x3004);
static constexpr System::Word GL_CLIP_PLANE5 = System::Word(0x3005);
static constexpr System::Word GL_COLOR_ARRAY = System::Word(0x8076);
static constexpr System::Word GL_COLOR_ARRAY_BUFFER_BINDING = System::Word(0x8898);
static constexpr System::Word GL_COLOR_ARRAY_POINTER = System::Word(0x8090);
static constexpr System::Word GL_COLOR_ARRAY_SIZE = System::Word(0x8081);
static constexpr System::Word GL_COLOR_ARRAY_STRIDE = System::Word(0x8083);
static constexpr System::Word GL_COLOR_ARRAY_TYPE = System::Word(0x8082);
static constexpr System::Word GL_COLOR_ATTACHMENT0 = System::Word(0x8ce0);
static constexpr System::Word GL_COLOR_ATTACHMENT0_OES = System::Word(0x8ce0);
static constexpr System::Word GL_COLOR_BUFFER_BIT = System::Word(0x4000);
static constexpr System::Word GL_COLOR_CLEAR_VALUE = System::Word(0xc22);
static constexpr System::Word GL_COLOR_EXT = System::Word(0x1800);
static constexpr System::Word GL_COLOR_LOGIC_OP = System::Word(0xbf2);
static constexpr System::Word GL_COLOR_MATERIAL = System::Word(0xb57);
static constexpr System::Word GL_COLOR_WRITEMASK = System::Word(0xc23);
static constexpr System::Word GL_COMBINE = System::Word(0x8570);
static constexpr System::Word GL_COMBINE_ALPHA = System::Word(0x8572);
static constexpr System::Word GL_COMBINE_RGB = System::Word(0x8571);
static constexpr System::Word GL_COMPARE_REF_TO_TEXTURE_EXT = System::Word(0x884e);
static constexpr System::Word GL_COMPILE_STATUS = System::Word(0x8b81);
static constexpr System::Word GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG = System::Word(0x8c03);
static constexpr System::Word GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG = System::Word(0x8c02);
static constexpr System::Word GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG = System::Word(0x8c01);
static constexpr System::Word GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG = System::Word(0x8c00);
static constexpr System::Word GL_COMPRESSED_TEXTURE_FORMATS = System::Word(0x86a3);
static constexpr System::Word GL_CONSTANT = System::Word(0x8576);
static constexpr System::Word GL_CONSTANT_ALPHA = System::Word(0x8003);
static constexpr System::Word GL_CONSTANT_ATTENUATION = System::Word(0x1207);
static constexpr System::Word GL_CONSTANT_COLOR = System::Word(0x8001);
static constexpr System::Word GL_COORD_REPLACE_OES = System::Word(0x8862);
static constexpr System::Word GL_COPY = System::Word(0x1503);
static constexpr System::Word GL_COPY_INVERTED = System::Word(0x150c);
static constexpr System::Word GL_CULL_FACE = System::Word(0xb44);
static constexpr System::Word GL_CULL_FACE_MODE = System::Word(0xb45);
static constexpr System::Word GL_CURRENT_COLOR = System::Word(0xb00);
static constexpr System::Word GL_CURRENT_NORMAL = System::Word(0xb02);
static constexpr System::Word GL_CURRENT_PALETTE_MATRIX_OES = System::Word(0x8843);
static constexpr System::Word GL_CURRENT_PROGRAM = System::Word(0x8b8d);
static constexpr System::Word GL_CURRENT_QUERY_EXT = System::Word(0x8865);
static constexpr System::Word GL_CURRENT_TEXTURE_COORDS = System::Word(0xb03);
static constexpr System::Word GL_CURRENT_VERTEX_ATTRIB = System::Word(0x8626);
static constexpr System::Word GL_CW = System::Word(0x900);
static constexpr System::Word GL_DECAL = System::Word(0x2101);
static constexpr System::Word GL_DECR = System::Word(0x1e03);
static constexpr System::Word GL_DECR_WRAP = System::Word(0x8508);
static constexpr System::Word GL_DECR_WRAP_OES = System::Word(0x8508);
static constexpr System::Word GL_DELETE_STATUS = System::Word(0x8b80);
static constexpr System::Word GL_DEPTH24_STENCIL8_OES = System::Word(0x88f0);
static constexpr System::Word GL_DEPTH_ATTACHMENT = System::Word(0x8d00);
static constexpr System::Word GL_DEPTH_ATTACHMENT_OES = System::Word(0x8d00);
static constexpr System::Word GL_DEPTH_BITS = System::Word(0xd56);
static constexpr System::Word GL_DEPTH_BUFFER_BIT = System::Word(0x100);
static constexpr System::Word GL_DEPTH_CLEAR_VALUE = System::Word(0xb73);
static constexpr System::Word GL_DEPTH_COMPONENT = System::Word(0x1902);
static constexpr System::Word GL_DEPTH_COMPONENT16 = System::Word(0x81a5);
static constexpr System::Word GL_DEPTH_COMPONENT16_OES = System::Word(0x81a5);
static constexpr System::Word GL_DEPTH_COMPONENT24_OES = System::Word(0x81a6);
static constexpr System::Word GL_DEPTH_EXT = System::Word(0x1801);
static constexpr System::Word GL_DEPTH_FUNC = System::Word(0xb74);
static constexpr System::Word GL_DEPTH_RANGE = System::Word(0xb70);
static constexpr System::Word GL_DEPTH_STENCIL_OES = System::Word(0x84f9);
static constexpr System::Word GL_DEPTH_TEST = System::Word(0xb71);
static constexpr System::Word GL_DEPTH_WRITEMASK = System::Word(0xb72);
static constexpr System::Word GL_DIFFUSE = System::Word(0x1201);
static constexpr System::Word GL_DITHER = System::Word(0xbd0);
static constexpr System::Word GL_DONT_CARE = System::Word(0x1100);
static constexpr System::Word GL_DOT3_RGB = System::Word(0x86ae);
static constexpr System::Word GL_DOT3_RGBA = System::Word(0x86af);
static constexpr System::Word GL_DRAW_FRAMEBUFFER_APPLE = System::Word(0x8ca9);
static constexpr System::Word GL_DRAW_FRAMEBUFFER_BINDING_APPLE = System::Word(0x8ca6);
static constexpr System::Word GL_DST_ALPHA = System::Word(0x304);
static constexpr System::Word GL_DST_COLOR = System::Word(0x306);
static constexpr System::Word GL_DYNAMIC_DRAW = System::Word(0x88e8);
static constexpr System::Word GL_ELEMENT_ARRAY_BUFFER = System::Word(0x8893);
static constexpr System::Word GL_ELEMENT_ARRAY_BUFFER_BINDING = System::Word(0x8895);
static constexpr System::Word GL_EMISSION = System::Word(0x1600);
static constexpr System::Word GL_EQUAL = System::Word(0x202);
static constexpr System::Word GL_EQUIV = System::Word(0x1509);
static constexpr System::Int8 GL_ES_VERSION_2_0 = System::Int8(0x1);
static constexpr System::Word GL_EXP = System::Word(0x800);
static constexpr System::Word GL_EXP2 = System::Word(0x801);
static constexpr System::Word GL_EXTENSIONS = System::Word(0x1f03);
static constexpr System::Int8 GL_EXT_blend_minmax = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_color_buffer_half_float = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_debug_label = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_debug_marker = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_discard_framebuffer = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_occlusion_query_boolean = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_read_format_bgra = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_separate_shader_objects = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_shader_texture_lod = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_shadow_samplers = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_texture_filter_anisotropic = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_texture_lod_bias = System::Int8(0x1);
static constexpr System::Int8 GL_EXT_texture_rg = System::Int8(0x1);
static constexpr System::Int8 GL_FALSE = System::Int8(0x0);
static constexpr System::Word GL_FASTEST = System::Word(0x1101);
static constexpr System::Word GL_FIXED = System::Word(0x140c);
static constexpr System::Word GL_FLAT = System::Word(0x1d00);
static constexpr System::Word GL_FLOAT = System::Word(0x1406);
static constexpr System::Word GL_FLOAT_MAT2 = System::Word(0x8b5a);
static constexpr System::Word GL_FLOAT_MAT3 = System::Word(0x8b5b);
static constexpr System::Word GL_FLOAT_MAT4 = System::Word(0x8b5c);
static constexpr System::Word GL_FLOAT_VEC2 = System::Word(0x8b50);
static constexpr System::Word GL_FLOAT_VEC3 = System::Word(0x8b51);
static constexpr System::Word GL_FLOAT_VEC4 = System::Word(0x8b52);
static constexpr System::Word GL_FOG = System::Word(0xb60);
static constexpr System::Word GL_FOG_COLOR = System::Word(0xb66);
static constexpr System::Word GL_FOG_DENSITY = System::Word(0xb62);
static constexpr System::Word GL_FOG_END = System::Word(0xb64);
static constexpr System::Word GL_FOG_HINT = System::Word(0xc54);
static constexpr System::Word GL_FOG_MODE = System::Word(0xb65);
static constexpr System::Word GL_FOG_START = System::Word(0xb63);
static constexpr System::Word GL_FRAGMENT_SHADER = System::Word(0x8b30);
static constexpr System::Int8 GL_FRAGMENT_SHADER_BIT_EXT = System::Int8(0x2);
static constexpr System::Word GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES = System::Word(0x8b8b);
static constexpr System::Word GL_FRAMEBUFFER = System::Word(0x8d40);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT = System::Word(0x8211);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = System::Word(0x8cd1);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES = System::Word(0x8cd1);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = System::Word(0x8cd0);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES = System::Word(0x8cd0);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = System::Word(0x8cd3);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES = System::Word(0x8cd3);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = System::Word(0x8cd2);
static constexpr System::Word GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES = System::Word(0x8cd2);
static constexpr System::Word GL_FRAMEBUFFER_BINDING = System::Word(0x8ca6);
static constexpr System::Word GL_FRAMEBUFFER_BINDING_OES = System::Word(0x8ca6);
static constexpr System::Word GL_FRAMEBUFFER_COMPLETE = System::Word(0x8cd5);
static constexpr System::Word GL_FRAMEBUFFER_COMPLETE_OES = System::Word(0x8cd5);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = System::Word(0x8cd6);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES = System::Word(0x8cd6);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = System::Word(0x8cd9);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES = System::Word(0x8cd9);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES = System::Word(0x8cda);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = System::Word(0x8cd7);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES = System::Word(0x8cd7);
static constexpr System::Word GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE = System::Word(0x8d56);
static constexpr System::Word GL_FRAMEBUFFER_OES = System::Word(0x8d40);
static constexpr System::Word GL_FRAMEBUFFER_UNSUPPORTED = System::Word(0x8cdd);
static constexpr System::Word GL_FRAMEBUFFER_UNSUPPORTED_OES = System::Word(0x8cdd);
static constexpr System::Word GL_FRONT = System::Word(0x404);
static constexpr System::Word GL_FRONT_AND_BACK = System::Word(0x408);
static constexpr System::Word GL_FRONT_FACE = System::Word(0xb46);
static constexpr System::Word GL_FUNC_ADD = System::Word(0x8006);
static constexpr System::Word GL_FUNC_ADD_OES = System::Word(0x8006);
static constexpr System::Word GL_FUNC_REVERSE_SUBTRACT = System::Word(0x800b);
static constexpr System::Word GL_FUNC_REVERSE_SUBTRACT_OES = System::Word(0x800b);
static constexpr System::Word GL_FUNC_SUBTRACT = System::Word(0x800a);
static constexpr System::Word GL_FUNC_SUBTRACT_OES = System::Word(0x800a);
static constexpr System::Word GL_GENERATE_MIPMAP = System::Word(0x8191);
static constexpr System::Word GL_GENERATE_MIPMAP_HINT = System::Word(0x8192);
static constexpr System::Word GL_GEQUAL = System::Word(0x206);
static constexpr System::Word GL_GREATER = System::Word(0x204);
static constexpr System::Word GL_GREEN_BITS = System::Word(0xd53);
static constexpr System::Word GL_HALF_FLOAT_OES = System::Word(0x8d61);
static constexpr System::Word GL_HIGH_FLOAT = System::Word(0x8df2);
static constexpr System::Word GL_HIGH_INT = System::Word(0x8df5);
static constexpr System::Int8 GL_IMG_read_format = System::Int8(0x1);
static constexpr System::Int8 GL_IMG_texture_compression_pvrtc = System::Int8(0x1);
static constexpr System::Word GL_IMPLEMENTATION_COLOR_READ_FORMAT = System::Word(0x8b9b);
static constexpr System::Word GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES = System::Word(0x8b9b);
static constexpr System::Word GL_IMPLEMENTATION_COLOR_READ_TYPE = System::Word(0x8b9a);
static constexpr System::Word GL_IMPLEMENTATION_COLOR_READ_TYPE_OES = System::Word(0x8b9a);
static constexpr System::Word GL_INCR = System::Word(0x1e02);
static constexpr System::Word GL_INCR_WRAP = System::Word(0x8507);
static constexpr System::Word GL_INCR_WRAP_OES = System::Word(0x8507);
static constexpr System::Word GL_INFO_LOG_LENGTH = System::Word(0x8b84);
static constexpr System::Word GL_INT = System::Word(0x1404);
static constexpr System::Word GL_INTERPOLATE = System::Word(0x8575);
static constexpr System::Word GL_INT_VEC2 = System::Word(0x8b53);
static constexpr System::Word GL_INT_VEC3 = System::Word(0x8b54);
static constexpr System::Word GL_INT_VEC4 = System::Word(0x8b55);
static constexpr System::Word GL_INVALID_ENUM = System::Word(0x500);
static constexpr System::Word GL_INVALID_FRAMEBUFFER_OPERATION = System::Word(0x506);
static constexpr System::Word GL_INVALID_FRAMEBUFFER_OPERATION_OES = System::Word(0x506);
static constexpr System::Word GL_INVALID_OPERATION = System::Word(0x502);
static constexpr System::Word GL_INVALID_VALUE = System::Word(0x501);
static constexpr System::Word GL_INVERT = System::Word(0x150a);
static constexpr System::Word GL_KEEP = System::Word(0x1e00);
static constexpr System::Word GL_LEQUAL = System::Word(0x203);
static constexpr System::Word GL_LESS = System::Word(0x201);
static constexpr System::Word GL_LIGHT0 = System::Word(0x4000);
static constexpr System::Word GL_LIGHT1 = System::Word(0x4001);
static constexpr System::Word GL_LIGHT2 = System::Word(0x4002);
static constexpr System::Word GL_LIGHT3 = System::Word(0x4003);
static constexpr System::Word GL_LIGHT4 = System::Word(0x4004);
static constexpr System::Word GL_LIGHT5 = System::Word(0x4005);
static constexpr System::Word GL_LIGHT6 = System::Word(0x4006);
static constexpr System::Word GL_LIGHT7 = System::Word(0x4007);
static constexpr System::Word GL_LIGHTING = System::Word(0xb50);
static constexpr System::Word GL_LIGHT_MODEL_AMBIENT = System::Word(0xb53);
static constexpr System::Word GL_LIGHT_MODEL_TWO_SIDE = System::Word(0xb52);
static constexpr System::Word GL_LINEAR = System::Word(0x2601);
static constexpr System::Word GL_LINEAR_ATTENUATION = System::Word(0x1208);
static constexpr System::Word GL_LINEAR_MIPMAP_LINEAR = System::Word(0x2703);
static constexpr System::Word GL_LINEAR_MIPMAP_NEAREST = System::Word(0x2701);
static constexpr System::Int8 GL_LINES = System::Int8(0x1);
static constexpr System::Int8 GL_LINE_LOOP = System::Int8(0x2);
static constexpr System::Word GL_LINE_SMOOTH = System::Word(0xb20);
static constexpr System::Word GL_LINE_SMOOTH_HINT = System::Word(0xc52);
static constexpr System::Int8 GL_LINE_STRIP = System::Int8(0x3);
static constexpr System::Word GL_LINE_WIDTH = System::Word(0xb21);
static constexpr System::Word GL_LINK_STATUS = System::Word(0x8b82);
static constexpr System::Word GL_LOGIC_OP_MODE = System::Word(0xbf0);
static constexpr System::Word GL_LOW_FLOAT = System::Word(0x8df0);
static constexpr System::Word GL_LOW_INT = System::Word(0x8df3);
static constexpr System::Word GL_LUMINANCE = System::Word(0x1909);
static constexpr System::Word GL_LUMINANCE_ALPHA = System::Word(0x190a);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES = System::Word(0x8b9e);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_OES = System::Word(0x8844);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_POINTER_OES = System::Word(0x8849);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_SIZE_OES = System::Word(0x8846);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_STRIDE_OES = System::Word(0x8848);
static constexpr System::Word GL_MATRIX_INDEX_ARRAY_TYPE_OES = System::Word(0x8847);
static constexpr System::Word GL_MATRIX_MODE = System::Word(0xba0);
static constexpr System::Word GL_MATRIX_PALETTE_OES = System::Word(0x8840);
static constexpr System::Word GL_MAX_CLIP_PLANES = System::Word(0xd32);
static constexpr System::Word GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = System::Word(0x8b4d);
static constexpr System::Word GL_MAX_CUBE_MAP_TEXTURE_SIZE = System::Word(0x851c);
static constexpr System::Word GL_MAX_EXT = System::Word(0x8008);
static constexpr System::Word GL_MAX_FRAGMENT_UNIFORM_VECTORS = System::Word(0x8dfd);
static constexpr System::Word GL_MAX_LIGHTS = System::Word(0xd31);
static constexpr System::Word GL_MAX_MODELVIEW_STACK_DEPTH = System::Word(0xd36);
static constexpr System::Word GL_MAX_PALETTE_MATRICES_OES = System::Word(0x8842);
static constexpr System::Word GL_MAX_PROJECTION_STACK_DEPTH = System::Word(0xd38);
static constexpr System::Word GL_MAX_RENDERBUFFER_SIZE = System::Word(0x84e8);
static constexpr System::Word GL_MAX_RENDERBUFFER_SIZE_OES = System::Word(0x84e8);
static constexpr System::Word GL_MAX_SAMPLES_APPLE = System::Word(0x8d57);
static constexpr System::Word GL_MAX_TEXTURE_IMAGE_UNITS = System::Word(0x8872);
static constexpr System::Word GL_MAX_TEXTURE_LOD_BIAS_EXT = System::Word(0x84fd);
static constexpr System::Word GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = System::Word(0x84ff);
static constexpr System::Word GL_MAX_TEXTURE_SIZE = System::Word(0xd33);
static constexpr System::Word GL_MAX_TEXTURE_STACK_DEPTH = System::Word(0xd39);
static constexpr System::Word GL_MAX_TEXTURE_UNITS = System::Word(0x84e2);
static constexpr System::Word GL_MAX_VARYING_VECTORS = System::Word(0x8dfc);
static constexpr System::Word GL_MAX_VERTEX_ATTRIBS = System::Word(0x8869);
static constexpr System::Word GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = System::Word(0x8b4c);
static constexpr System::Word GL_MAX_VERTEX_UNIFORM_VECTORS = System::Word(0x8dfb);
static constexpr System::Word GL_MAX_VERTEX_UNITS_OES = System::Word(0x86a4);
static constexpr System::Word GL_MAX_VIEWPORT_DIMS = System::Word(0xd3a);
static constexpr System::Word GL_MEDIUM_FLOAT = System::Word(0x8df1);
static constexpr System::Word GL_MEDIUM_INT = System::Word(0x8df4);
static constexpr System::Word GL_MIN_EXT = System::Word(0x8007);
static constexpr System::Word GL_MIRRORED_REPEAT = System::Word(0x8370);
static constexpr System::Word GL_MIRRORED_REPEAT_OES = System::Word(0x8370);
static constexpr System::Word GL_MODELVIEW = System::Word(0x1700);
static constexpr System::Word GL_MODELVIEW_MATRIX = System::Word(0xba6);
static constexpr System::Word GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES = System::Word(0x898d);
static constexpr System::Word GL_MODELVIEW_STACK_DEPTH = System::Word(0xba3);
static constexpr System::Word GL_MODULATE = System::Word(0x2100);
static constexpr System::Word GL_MULTISAMPLE = System::Word(0x809d);
static constexpr System::Word GL_NAND = System::Word(0x150e);
static constexpr System::Word GL_NEAREST = System::Word(0x2600);
static constexpr System::Word GL_NEAREST_MIPMAP_LINEAR = System::Word(0x2702);
static constexpr System::Word GL_NEAREST_MIPMAP_NEAREST = System::Word(0x2700);
static constexpr System::Word GL_NEVER = System::Word(0x200);
static constexpr System::Word GL_NICEST = System::Word(0x1102);
static constexpr System::Int8 GL_NONE = System::Int8(0x0);
static constexpr System::Word GL_NOOP = System::Word(0x1505);
static constexpr System::Word GL_NOR = System::Word(0x1508);
static constexpr System::Word GL_NORMALIZE = System::Word(0xba1);
static constexpr System::Word GL_NORMAL_ARRAY = System::Word(0x8075);
static constexpr System::Word GL_NORMAL_ARRAY_BUFFER_BINDING = System::Word(0x8897);
static constexpr System::Word GL_NORMAL_ARRAY_POINTER = System::Word(0x808f);
static constexpr System::Word GL_NORMAL_ARRAY_STRIDE = System::Word(0x807f);
static constexpr System::Word GL_NORMAL_ARRAY_TYPE = System::Word(0x807e);
static constexpr System::Word GL_NOTEQUAL = System::Word(0x205);
static constexpr System::Int8 GL_NO_ERROR = System::Int8(0x0);
static constexpr System::Word GL_NUM_COMPRESSED_TEXTURE_FORMATS = System::Word(0x86a2);
static constexpr System::Word GL_NUM_SHADER_BINARY_FORMATS = System::Word(0x8df9);
static constexpr System::Int8 GL_OES_VERSION_1_0 = System::Int8(0x1);
static constexpr System::Int8 GL_OES_VERSION_1_1 = System::Int8(0x1);
static constexpr System::Int8 GL_OES_blend_equation_separate = System::Int8(0x1);
static constexpr System::Int8 GL_OES_blend_func_separate = System::Int8(0x1);
static constexpr System::Int8 GL_OES_blend_subtract = System::Int8(0x1);
static constexpr System::Int8 GL_OES_byte_coordinates = System::Int8(0x1);
static constexpr System::Int8 GL_OES_compressed_paletted_texture = System::Int8(0x1);
static constexpr System::Int8 GL_OES_depth24 = System::Int8(0x1);
static constexpr System::Int8 GL_OES_depth_texture = System::Int8(0x1);
static constexpr System::Int8 GL_OES_draw_texture = System::Int8(0x1);
static constexpr System::Int8 GL_OES_element_index_uint = System::Int8(0x1);
static constexpr System::Int8 GL_OES_fbo_render_mipmap = System::Int8(0x1);
static constexpr System::Int8 GL_OES_fixed_point = System::Int8(0x1);
static constexpr System::Int8 GL_OES_framebuffer_object = System::Int8(0x1);
static constexpr System::Int8 GL_OES_mapbuffer = System::Int8(0x1);
static constexpr System::Int8 GL_OES_matrix_get = System::Int8(0x1);
static constexpr System::Int8 GL_OES_matrix_palette = System::Int8(0x1);
static constexpr System::Int8 GL_OES_packed_depth_stencil = System::Int8(0x1);
static constexpr System::Int8 GL_OES_point_size_array = System::Int8(0x1);
static constexpr System::Int8 GL_OES_point_sprite = System::Int8(0x1);
static constexpr System::Int8 GL_OES_read_format = System::Int8(0x1);
static constexpr System::Int8 GL_OES_rgb8_rgba8 = System::Int8(0x1);
static constexpr System::Int8 GL_OES_single_precision = System::Int8(0x1);
static constexpr System::Int8 GL_OES_standard_derivatives = System::Int8(0x1);
static constexpr System::Int8 GL_OES_stencil8 = System::Int8(0x1);
static constexpr System::Int8 GL_OES_stencil_wrap = System::Int8(0x1);
static constexpr System::Int8 GL_OES_texture_float = System::Int8(0x1);
static constexpr System::Int8 GL_OES_texture_half_float = System::Int8(0x1);
static constexpr System::Int8 GL_OES_texture_mirrored_repeat = System::Int8(0x1);
static constexpr System::Int8 GL_OES_vertex_array_object = System::Int8(0x1);
static constexpr System::Int8 GL_ONE = System::Int8(0x1);
static constexpr System::Word GL_ONE_MINUS_CONSTANT_ALPHA = System::Word(0x8004);
static constexpr System::Word GL_ONE_MINUS_CONSTANT_COLOR = System::Word(0x8002);
static constexpr System::Word GL_ONE_MINUS_DST_ALPHA = System::Word(0x305);
static constexpr System::Word GL_ONE_MINUS_DST_COLOR = System::Word(0x307);
static constexpr System::Word GL_ONE_MINUS_SRC_ALPHA = System::Word(0x303);
static constexpr System::Word GL_ONE_MINUS_SRC_COLOR = System::Word(0x301);
static constexpr System::Word GL_OPERAND0_ALPHA = System::Word(0x8598);
static constexpr System::Word GL_OPERAND0_RGB = System::Word(0x8590);
static constexpr System::Word GL_OPERAND1_ALPHA = System::Word(0x8599);
static constexpr System::Word GL_OPERAND1_RGB = System::Word(0x8591);
static constexpr System::Word GL_OPERAND2_ALPHA = System::Word(0x859a);
static constexpr System::Word GL_OPERAND2_RGB = System::Word(0x8592);
static constexpr System::Word GL_OR = System::Word(0x1507);
static constexpr System::Word GL_OR_INVERTED = System::Word(0x150d);
static constexpr System::Word GL_OR_REVERSE = System::Word(0x150b);
static constexpr System::Word GL_OUT_OF_MEMORY = System::Word(0x505);
static constexpr System::Word GL_PACK_ALIGNMENT = System::Word(0xd05);
static constexpr System::Word GL_PALETTE4_R5_G6_B5_OES = System::Word(0x8b92);
static constexpr System::Word GL_PALETTE4_RGB5_A1_OES = System::Word(0x8b94);
static constexpr System::Word GL_PALETTE4_RGB8_OES = System::Word(0x8b90);
static constexpr System::Word GL_PALETTE4_RGBA4_OES = System::Word(0x8b93);
static constexpr System::Word GL_PALETTE4_RGBA8_OES = System::Word(0x8b91);
static constexpr System::Word GL_PALETTE8_R5_G6_B5_OES = System::Word(0x8b97);
static constexpr System::Word GL_PALETTE8_RGB5_A1_OES = System::Word(0x8b99);
static constexpr System::Word GL_PALETTE8_RGB8_OES = System::Word(0x8b95);
static constexpr System::Word GL_PALETTE8_RGBA4_OES = System::Word(0x8b98);
static constexpr System::Word GL_PALETTE8_RGBA8_OES = System::Word(0x8b96);
static constexpr System::Word GL_PERSPECTIVE_CORRECTION_HINT = System::Word(0xc50);
static constexpr System::Int8 GL_POINTS = System::Int8(0x0);
static constexpr System::Word GL_POINT_DISTANCE_ATTENUATION = System::Word(0x8129);
static constexpr System::Word GL_POINT_FADE_THRESHOLD_SIZE = System::Word(0x8128);
static constexpr System::Word GL_POINT_SIZE = System::Word(0xb11);
static constexpr System::Word GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES = System::Word(0x8b9f);
static constexpr System::Word GL_POINT_SIZE_ARRAY_OES = System::Word(0x8b9c);
static constexpr System::Word GL_POINT_SIZE_ARRAY_POINTER_OES = System::Word(0x898c);
static constexpr System::Word GL_POINT_SIZE_ARRAY_STRIDE_OES = System::Word(0x898b);
static constexpr System::Word GL_POINT_SIZE_ARRAY_TYPE_OES = System::Word(0x898a);
static constexpr System::Word GL_POINT_SIZE_MAX = System::Word(0x8127);
static constexpr System::Word GL_POINT_SIZE_MIN = System::Word(0x8126);
static constexpr System::Word GL_POINT_SMOOTH = System::Word(0xb10);
static constexpr System::Word GL_POINT_SMOOTH_HINT = System::Word(0xc51);
static constexpr System::Word GL_POINT_SPRITE_OES = System::Word(0x8861);
static constexpr System::Word GL_POLYGON_OFFSET_FACTOR = System::Word(0x8038);
static constexpr System::Word GL_POLYGON_OFFSET_FILL = System::Word(0x8037);
static constexpr System::Word GL_POLYGON_OFFSET_UNITS = System::Word(0x2a00);
static constexpr System::Word GL_POSITION = System::Word(0x1203);
static constexpr System::Word GL_PREVIOUS = System::Word(0x8578);
static constexpr System::Word GL_PRIMARY_COLOR = System::Word(0x8577);
static constexpr System::Word GL_PROGRAM_OBJECT_EXT = System::Word(0x8b40);
static constexpr System::Word GL_PROGRAM_PIPELINE_BINDING_EXT = System::Word(0x825a);
static constexpr System::Word GL_PROGRAM_PIPELINE_OBJECT_EXT = System::Word(0x8a4f);
static constexpr System::Word GL_PROGRAM_SEPARABLE_EXT = System::Word(0x8258);
static constexpr System::Word GL_PROJECTION = System::Word(0x1701);
static constexpr System::Word GL_PROJECTION_MATRIX = System::Word(0xba7);
static constexpr System::Word GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES = System::Word(0x898e);
static constexpr System::Word GL_PROJECTION_STACK_DEPTH = System::Word(0xba4);
static constexpr System::Word GL_QUADRATIC_ATTENUATION = System::Word(0x1209);
static constexpr System::Word GL_QUERY_OBJECT_EXT = System::Word(0x9153);
static constexpr System::Word GL_QUERY_RESULT_AVAILABLE_EXT = System::Word(0x8867);
static constexpr System::Word GL_QUERY_RESULT_EXT = System::Word(0x8866);
static constexpr System::Word GL_R16F_EXT = System::Word(0x822d);
static constexpr System::Word GL_R8_EXT = System::Word(0x8229);
static constexpr System::Word GL_READ_FRAMEBUFFER_APPLE = System::Word(0x8ca8);
static constexpr System::Word GL_READ_FRAMEBUFFER_BINDING_APPLE = System::Word(0x8caa);
static constexpr System::Word GL_RED_BITS = System::Word(0xd52);
static constexpr System::Word GL_RED_EXT = System::Word(0x1903);
static constexpr System::Word GL_RENDERBUFFER = System::Word(0x8d41);
static constexpr System::Word GL_RENDERBUFFER_ALPHA_SIZE = System::Word(0x8d53);
static constexpr System::Word GL_RENDERBUFFER_ALPHA_SIZE_OES = System::Word(0x8d53);
static constexpr System::Word GL_RENDERBUFFER_BINDING = System::Word(0x8ca7);
static constexpr System::Word GL_RENDERBUFFER_BINDING_OES = System::Word(0x8ca7);
static constexpr System::Word GL_RENDERBUFFER_BLUE_SIZE = System::Word(0x8d52);
static constexpr System::Word GL_RENDERBUFFER_BLUE_SIZE_OES = System::Word(0x8d52);
static constexpr System::Word GL_RENDERBUFFER_DEPTH_SIZE = System::Word(0x8d54);
static constexpr System::Word GL_RENDERBUFFER_DEPTH_SIZE_OES = System::Word(0x8d54);
static constexpr System::Word GL_RENDERBUFFER_GREEN_SIZE = System::Word(0x8d51);
static constexpr System::Word GL_RENDERBUFFER_GREEN_SIZE_OES = System::Word(0x8d51);
static constexpr System::Word GL_RENDERBUFFER_HEIGHT = System::Word(0x8d43);
static constexpr System::Word GL_RENDERBUFFER_HEIGHT_OES = System::Word(0x8d43);
static constexpr System::Word GL_RENDERBUFFER_INTERNAL_FORMAT = System::Word(0x8d44);
static constexpr System::Word GL_RENDERBUFFER_INTERNAL_FORMAT_OES = System::Word(0x8d44);
static constexpr System::Word GL_RENDERBUFFER_OES = System::Word(0x8d41);
static constexpr System::Word GL_RENDERBUFFER_RED_SIZE = System::Word(0x8d50);
static constexpr System::Word GL_RENDERBUFFER_RED_SIZE_OES = System::Word(0x8d50);
static constexpr System::Word GL_RENDERBUFFER_SAMPLES_APPLE = System::Word(0x8cab);
static constexpr System::Word GL_RENDERBUFFER_STENCIL_SIZE = System::Word(0x8d55);
static constexpr System::Word GL_RENDERBUFFER_STENCIL_SIZE_OES = System::Word(0x8d55);
static constexpr System::Word GL_RENDERBUFFER_WIDTH = System::Word(0x8d42);
static constexpr System::Word GL_RENDERBUFFER_WIDTH_OES = System::Word(0x8d42);
static constexpr System::Word GL_RENDERER = System::Word(0x1f01);
static constexpr System::Word GL_REPEAT = System::Word(0x2901);
static constexpr System::Word GL_REPLACE = System::Word(0x1e01);
static constexpr System::Word GL_RESCALE_NORMAL = System::Word(0x803a);
static constexpr System::Word GL_RG16F_EXT = System::Word(0x822f);
static constexpr System::Word GL_RG8_EXT = System::Word(0x822b);
static constexpr System::Word GL_RGB = System::Word(0x1907);
static constexpr System::Word GL_RGB16F_EXT = System::Word(0x881b);
static constexpr System::Word GL_RGB565 = System::Word(0x8d62);
static constexpr System::Word GL_RGB565_OES = System::Word(0x8d62);
static constexpr System::Word GL_RGB5_A1 = System::Word(0x8057);
static constexpr System::Word GL_RGB5_A1_OES = System::Word(0x8057);
static constexpr System::Word GL_RGB8_OES = System::Word(0x8051);
static constexpr System::Word GL_RGBA = System::Word(0x1908);
static constexpr System::Word GL_RGBA16F_EXT = System::Word(0x881a);
static constexpr System::Word GL_RGBA4 = System::Word(0x8056);
static constexpr System::Word GL_RGBA4_OES = System::Word(0x8056);
static constexpr System::Word GL_RGBA8_OES = System::Word(0x8058);
static constexpr System::Word GL_RGB_422_APPLE = System::Word(0x8a1f);
static constexpr System::Word GL_RGB_SCALE = System::Word(0x8573);
static constexpr System::Word GL_RG_EXT = System::Word(0x8227);
static constexpr System::Word GL_SAMPLER_2D = System::Word(0x8b5e);
static constexpr System::Word GL_SAMPLER_CUBE = System::Word(0x8b60);
static constexpr System::Word GL_SAMPLES = System::Word(0x80a9);
static constexpr System::Word GL_SAMPLE_ALPHA_TO_COVERAGE = System::Word(0x809e);
static constexpr System::Word GL_SAMPLE_ALPHA_TO_ONE = System::Word(0x809f);
static constexpr System::Word GL_SAMPLE_BUFFERS = System::Word(0x80a8);
static constexpr System::Word GL_SAMPLE_COVERAGE = System::Word(0x80a0);
static constexpr System::Word GL_SAMPLE_COVERAGE_INVERT = System::Word(0x80ab);
static constexpr System::Word GL_SAMPLE_COVERAGE_VALUE = System::Word(0x80aa);
static constexpr System::Word GL_SCISSOR_BOX = System::Word(0xc10);
static constexpr System::Word GL_SCISSOR_TEST = System::Word(0xc11);
static constexpr System::Word GL_SET = System::Word(0x150f);
static constexpr System::Word GL_SHADER_BINARY_FORMATS = System::Word(0x8df8);
static constexpr System::Word GL_SHADER_COMPILER = System::Word(0x8dfa);
static constexpr System::Word GL_SHADER_OBJECT_EXT = System::Word(0x8b48);
static constexpr System::Word GL_SHADER_SOURCE_LENGTH = System::Word(0x8b88);
static constexpr System::Word GL_SHADER_TYPE = System::Word(0x8b4f);
static constexpr System::Word GL_SHADE_MODEL = System::Word(0xb54);
static constexpr System::Word GL_SHADING_LANGUAGE_VERSION = System::Word(0x8b8c);
static constexpr System::Word GL_SHININESS = System::Word(0x1601);
static constexpr System::Word GL_SHORT = System::Word(0x1402);
static constexpr System::Word GL_SMOOTH = System::Word(0x1d01);
static constexpr System::Word GL_SMOOTH_LINE_WIDTH_RANGE = System::Word(0xb22);
static constexpr System::Word GL_SMOOTH_POINT_SIZE_RANGE = System::Word(0xb12);
static constexpr System::Word GL_SPECULAR = System::Word(0x1202);
static constexpr System::Word GL_SPOT_CUTOFF = System::Word(0x1206);
static constexpr System::Word GL_SPOT_DIRECTION = System::Word(0x1204);
static constexpr System::Word GL_SPOT_EXPONENT = System::Word(0x1205);
static constexpr System::Word GL_SRC0_ALPHA = System::Word(0x8588);
static constexpr System::Word GL_SRC0_RGB = System::Word(0x8580);
static constexpr System::Word GL_SRC1_ALPHA = System::Word(0x8589);
static constexpr System::Word GL_SRC1_RGB = System::Word(0x8581);
static constexpr System::Word GL_SRC2_ALPHA = System::Word(0x858a);
static constexpr System::Word GL_SRC2_RGB = System::Word(0x8582);
static constexpr System::Word GL_SRC_ALPHA = System::Word(0x302);
static constexpr System::Word GL_SRC_ALPHA_SATURATE = System::Word(0x308);
static constexpr System::Word GL_SRC_COLOR = System::Word(0x300);
static constexpr System::Word GL_STACK_OVERFLOW = System::Word(0x503);
static constexpr System::Word GL_STACK_UNDERFLOW = System::Word(0x504);
static constexpr System::Word GL_STATIC_DRAW = System::Word(0x88e4);
static constexpr System::Word GL_STENCIL_ATTACHMENT = System::Word(0x8d20);
static constexpr System::Word GL_STENCIL_ATTACHMENT_OES = System::Word(0x8d20);
static constexpr System::Word GL_STENCIL_BACK_FAIL = System::Word(0x8801);
static constexpr System::Word GL_STENCIL_BACK_FUNC = System::Word(0x8800);
static constexpr System::Word GL_STENCIL_BACK_PASS_DEPTH_FAIL = System::Word(0x8802);
static constexpr System::Word GL_STENCIL_BACK_PASS_DEPTH_PASS = System::Word(0x8803);
static constexpr System::Word GL_STENCIL_BACK_REF = System::Word(0x8ca3);
static constexpr System::Word GL_STENCIL_BACK_VALUE_MASK = System::Word(0x8ca4);
static constexpr System::Word GL_STENCIL_BACK_WRITEMASK = System::Word(0x8ca5);
static constexpr System::Word GL_STENCIL_BITS = System::Word(0xd57);
static constexpr System::Word GL_STENCIL_BUFFER_BIT = System::Word(0x400);
static constexpr System::Word GL_STENCIL_CLEAR_VALUE = System::Word(0xb91);
static constexpr System::Word GL_STENCIL_EXT = System::Word(0x1802);
static constexpr System::Word GL_STENCIL_FAIL = System::Word(0xb94);
static constexpr System::Word GL_STENCIL_FUNC = System::Word(0xb92);
static constexpr System::Word GL_STENCIL_INDEX = System::Word(0x1901);
static constexpr System::Word GL_STENCIL_INDEX8 = System::Word(0x8d48);
static constexpr System::Word GL_STENCIL_INDEX8_OES = System::Word(0x8d48);
static constexpr System::Word GL_STENCIL_PASS_DEPTH_FAIL = System::Word(0xb95);
static constexpr System::Word GL_STENCIL_PASS_DEPTH_PASS = System::Word(0xb96);
static constexpr System::Word GL_STENCIL_REF = System::Word(0xb97);
static constexpr System::Word GL_STENCIL_TEST = System::Word(0xb90);
static constexpr System::Word GL_STENCIL_VALUE_MASK = System::Word(0xb93);
static constexpr System::Word GL_STENCIL_WRITEMASK = System::Word(0xb98);
static constexpr System::Word GL_STREAM_DRAW = System::Word(0x88e0);
static constexpr System::Word GL_SUBPIXEL_BITS = System::Word(0xd50);
static constexpr System::Word GL_SUBTRACT = System::Word(0x84e7);
static constexpr System::Word GL_TEXTURE = System::Word(0x1702);
static constexpr System::Word GL_TEXTURE0 = System::Word(0x84c0);
static constexpr System::Word GL_TEXTURE1 = System::Word(0x84c1);
static constexpr System::Word GL_TEXTURE10 = System::Word(0x84ca);
static constexpr System::Word GL_TEXTURE11 = System::Word(0x84cb);
static constexpr System::Word GL_TEXTURE12 = System::Word(0x84cc);
static constexpr System::Word GL_TEXTURE13 = System::Word(0x84cd);
static constexpr System::Word GL_TEXTURE14 = System::Word(0x84ce);
static constexpr System::Word GL_TEXTURE15 = System::Word(0x84cf);
static constexpr System::Word GL_TEXTURE16 = System::Word(0x84d0);
static constexpr System::Word GL_TEXTURE17 = System::Word(0x84d1);
static constexpr System::Word GL_TEXTURE18 = System::Word(0x84d2);
static constexpr System::Word GL_TEXTURE19 = System::Word(0x84d3);
static constexpr System::Word GL_TEXTURE2 = System::Word(0x84c2);
static constexpr System::Word GL_TEXTURE20 = System::Word(0x84d4);
static constexpr System::Word GL_TEXTURE21 = System::Word(0x84d5);
static constexpr System::Word GL_TEXTURE22 = System::Word(0x84d6);
static constexpr System::Word GL_TEXTURE23 = System::Word(0x84d7);
static constexpr System::Word GL_TEXTURE24 = System::Word(0x84d8);
static constexpr System::Word GL_TEXTURE25 = System::Word(0x84d9);
static constexpr System::Word GL_TEXTURE26 = System::Word(0x84da);
static constexpr System::Word GL_TEXTURE27 = System::Word(0x84db);
static constexpr System::Word GL_TEXTURE28 = System::Word(0x84dc);
static constexpr System::Word GL_TEXTURE29 = System::Word(0x84dd);
static constexpr System::Word GL_TEXTURE3 = System::Word(0x84c3);
static constexpr System::Word GL_TEXTURE30 = System::Word(0x84de);
static constexpr System::Word GL_TEXTURE31 = System::Word(0x84df);
static constexpr System::Word GL_TEXTURE4 = System::Word(0x84c4);
static constexpr System::Word GL_TEXTURE5 = System::Word(0x84c5);
static constexpr System::Word GL_TEXTURE6 = System::Word(0x84c6);
static constexpr System::Word GL_TEXTURE7 = System::Word(0x84c7);
static constexpr System::Word GL_TEXTURE8 = System::Word(0x84c8);
static constexpr System::Word GL_TEXTURE9 = System::Word(0x84c9);
static constexpr System::Word GL_TEXTURE_2D = System::Word(0xde1);
static constexpr System::Word GL_TEXTURE_BINDING_2D = System::Word(0x8069);
static constexpr System::Word GL_TEXTURE_BINDING_CUBE_MAP = System::Word(0x8514);
static constexpr System::Word GL_TEXTURE_COMPARE_FUNC_EXT = System::Word(0x884d);
static constexpr System::Word GL_TEXTURE_COMPARE_MODE_EXT = System::Word(0x884c);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY = System::Word(0x8078);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = System::Word(0x889a);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY_POINTER = System::Word(0x8092);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY_SIZE = System::Word(0x8088);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY_STRIDE = System::Word(0x808a);
static constexpr System::Word GL_TEXTURE_COORD_ARRAY_TYPE = System::Word(0x8089);
static constexpr System::Word GL_TEXTURE_CROP_RECT_OES = System::Word(0x8b9d);
static constexpr System::Word GL_TEXTURE_CUBE_MAP = System::Word(0x8513);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_NEGATIVE_X = System::Word(0x8516);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = System::Word(0x8518);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = System::Word(0x851a);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_POSITIVE_X = System::Word(0x8515);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_POSITIVE_Y = System::Word(0x8517);
static constexpr System::Word GL_TEXTURE_CUBE_MAP_POSITIVE_Z = System::Word(0x8519);
static constexpr System::Word GL_TEXTURE_ENV = System::Word(0x2300);
static constexpr System::Word GL_TEXTURE_ENV_COLOR = System::Word(0x2201);
static constexpr System::Word GL_TEXTURE_ENV_MODE = System::Word(0x2200);
static constexpr System::Word GL_TEXTURE_FILTER_CONTROL_EXT = System::Word(0x8500);
static constexpr System::Word GL_TEXTURE_LOD_BIAS_EXT = System::Word(0x8501);
static constexpr System::Word GL_TEXTURE_MAG_FILTER = System::Word(0x2800);
static constexpr System::Word GL_TEXTURE_MATRIX = System::Word(0xba8);
static constexpr System::Word GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES = System::Word(0x898f);
static constexpr System::Word GL_TEXTURE_MAX_ANISOTROPY_EXT = System::Word(0x84fe);
static constexpr System::Word GL_TEXTURE_MAX_LEVEL_APPLE = System::Word(0x813d);
static constexpr System::Word GL_TEXTURE_MIN_FILTER = System::Word(0x2801);
static constexpr System::Word GL_TEXTURE_STACK_DEPTH = System::Word(0xba5);
static constexpr System::Word GL_TEXTURE_WRAP_S = System::Word(0x2802);
static constexpr System::Word GL_TEXTURE_WRAP_T = System::Word(0x2803);
static constexpr System::Int8 GL_TRIANGLES = System::Int8(0x4);
static constexpr System::Int8 GL_TRIANGLE_FAN = System::Int8(0x6);
static constexpr System::Int8 GL_TRIANGLE_STRIP = System::Int8(0x5);
static constexpr System::Int8 GL_TRUE = System::Int8(0x1);
static constexpr System::Word GL_UNPACK_ALIGNMENT = System::Word(0xcf5);
static constexpr System::Word GL_UNSIGNED_BYTE = System::Word(0x1401);
static constexpr System::Word GL_UNSIGNED_INT = System::Word(0x1405);
static constexpr System::Word GL_UNSIGNED_INT_24_8_OES = System::Word(0x84fa);
static constexpr System::Word GL_UNSIGNED_INT_OES = System::Word(0x1405);
static constexpr System::Word GL_UNSIGNED_NORMALIZED_EXT = System::Word(0x8c17);
static constexpr System::Word GL_UNSIGNED_SHORT = System::Word(0x1403);
static constexpr System::Word GL_UNSIGNED_SHORT_1_5_5_5_REV = System::Word(0x8366);
static constexpr System::Word GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT = System::Word(0x8366);
static constexpr System::Word GL_UNSIGNED_SHORT_4_4_4_4 = System::Word(0x8033);
static constexpr System::Word GL_UNSIGNED_SHORT_4_4_4_4_REV = System::Word(0x8365);
static constexpr System::Word GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT = System::Word(0x8365);
static constexpr System::Word GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG = System::Word(0x8365);
static constexpr System::Word GL_UNSIGNED_SHORT_5_5_5_1 = System::Word(0x8034);
static constexpr System::Word GL_UNSIGNED_SHORT_5_6_5 = System::Word(0x8363);
static constexpr System::Word GL_UNSIGNED_SHORT_8_8_APPLE = System::Word(0x85ba);
static constexpr System::Word GL_UNSIGNED_SHORT_8_8_REV_APPLE = System::Word(0x85bb);
static constexpr System::Word GL_VALIDATE_STATUS = System::Word(0x8b83);
static constexpr System::Word GL_VENDOR = System::Word(0x1f00);
static constexpr System::Word GL_VERSION = System::Word(0x1f02);
static constexpr System::Int8 GL_VERSION_ES_CL_1_0 = System::Int8(0x1);
static constexpr System::Int8 GL_VERSION_ES_CL_1_1 = System::Int8(0x1);
static constexpr System::Int8 GL_VERSION_ES_CM_1_0 = System::Int8(0x1);
static constexpr System::Int8 GL_VERSION_ES_CM_1_1 = System::Int8(0x1);
static constexpr System::Word GL_VERTEX_ARRAY = System::Word(0x8074);
static constexpr System::Word GL_VERTEX_ARRAY_BINDING_OES = System::Word(0x85b5);
static constexpr System::Word GL_VERTEX_ARRAY_BUFFER_BINDING = System::Word(0x8896);
static constexpr System::Word GL_VERTEX_ARRAY_OBJECT_EXT = System::Word(0x9154);
static constexpr System::Word GL_VERTEX_ARRAY_POINTER = System::Word(0x808e);
static constexpr System::Word GL_VERTEX_ARRAY_SIZE = System::Word(0x807a);
static constexpr System::Word GL_VERTEX_ARRAY_STRIDE = System::Word(0x807c);
static constexpr System::Word GL_VERTEX_ARRAY_TYPE = System::Word(0x807b);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = System::Word(0x889f);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_ENABLED = System::Word(0x8622);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = System::Word(0x886a);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_POINTER = System::Word(0x8645);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_SIZE = System::Word(0x8623);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_STRIDE = System::Word(0x8624);
static constexpr System::Word GL_VERTEX_ATTRIB_ARRAY_TYPE = System::Word(0x8625);
static constexpr System::Word GL_VERTEX_SHADER = System::Word(0x8b31);
static constexpr System::Int8 GL_VERTEX_SHADER_BIT_EXT = System::Int8(0x1);
static constexpr System::Word GL_VIEWPORT = System::Word(0xba2);
static constexpr System::Word GL_WEIGHT_ARRAY_BUFFER_BINDING_OES = System::Word(0x889e);
static constexpr System::Word GL_WEIGHT_ARRAY_OES = System::Word(0x86ad);
static constexpr System::Word GL_WEIGHT_ARRAY_POINTER_OES = System::Word(0x86ac);
static constexpr System::Word GL_WEIGHT_ARRAY_SIZE_OES = System::Word(0x86ab);
static constexpr System::Word GL_WEIGHT_ARRAY_STRIDE_OES = System::Word(0x86aa);
static constexpr System::Word GL_WEIGHT_ARRAY_TYPE_OES = System::Word(0x86a9);
static constexpr System::Word GL_WRITE_ONLY_OES = System::Word(0x88b9);
static constexpr System::Word GL_XOR = System::Word(0x1506);
static constexpr System::Int8 GL_ZERO = System::Int8(0x0);
static constexpr System::Int8 kEAGLRenderingAPIOpenGLES1 = System::Int8(0x1);
static constexpr System::Int8 kEAGLRenderingAPIOpenGLES2 = System::Int8(0x2);
#define libOpenGLES u"/System/Library/Frameworks/OpenGLES.framework/OpenGLES"
extern "C" void __cdecl EAGLGetVersion(System::PCardinal major, System::PCardinal minor);
extern "C" void __cdecl glActiveShaderProgramEXT(unsigned pipeline, unsigned program_);
extern "C" void __cdecl glActiveTexture(unsigned texture);
extern "C" void __cdecl glAlphaFunc(unsigned func, float ref);
extern "C" void __cdecl glAlphaFuncx(unsigned func, int ref);
extern "C" void __cdecl glAttachShader(unsigned program_, unsigned shader);
extern "C" void __cdecl glBeginQueryEXT(unsigned target, unsigned id);
extern "C" void __cdecl glBindAttribLocation(unsigned program_, unsigned index, char * name);
extern "C" void __cdecl glBindBuffer(unsigned target, unsigned buffer);
extern "C" void __cdecl glBindFramebuffer(unsigned target, unsigned framebuffer);
extern "C" void __cdecl glBindFramebufferOES(unsigned target, unsigned framebuffer);
extern "C" void __cdecl glBindProgramPipelineEXT(unsigned pipeline);
extern "C" void __cdecl glBindRenderbuffer(unsigned target, unsigned renderbuffer);
extern "C" void __cdecl glBindRenderbufferOES(unsigned target, unsigned renderbuffer);
extern "C" void __cdecl glBindTexture(unsigned target, unsigned texture);
extern "C" void __cdecl glBindVertexArrayOES(unsigned array_);
extern "C" void __cdecl glBlendColor(float red, float green, float blue, float alpha);
extern "C" void __cdecl glBlendEquation(unsigned mode);
extern "C" void __cdecl glBlendEquationOES(unsigned mode);
extern "C" void __cdecl glBlendEquationSeparate(unsigned modeRGB, unsigned modeAlpha);
extern "C" void __cdecl glBlendEquationSeparateOES(unsigned modeRGB, unsigned modeAlpha);
extern "C" void __cdecl glBlendFunc(unsigned sfactor, unsigned dfactor);
extern "C" void __cdecl glBlendFuncSeparate(unsigned srcRGB, unsigned dstRGB, unsigned srcAlpha, unsigned dstAlpha);
extern "C" void __cdecl glBlendFuncSeparateOES(unsigned srcRGB, unsigned dstRGB, unsigned srcAlpha, unsigned dstAlpha);
extern "C" void __cdecl glBufferData(unsigned target, NativeInt size, void * data, unsigned usage);
extern "C" void __cdecl glBufferSubData(unsigned target, NativeInt offset, NativeInt size, void * data);
extern "C" unsigned __cdecl glCheckFramebufferStatus(unsigned target);
extern "C" unsigned __cdecl glCheckFramebufferStatusOES(unsigned target);
extern "C" void __cdecl glClear(unsigned mask);
extern "C" void __cdecl glClearColor(float red, float green, float blue, float alpha);
extern "C" void __cdecl glClearColorx(int red, int green, int blue, int alpha);
extern "C" void __cdecl glClearDepthf(float depth);
extern "C" void __cdecl glClearDepthx(int depth);
extern "C" void __cdecl glClearStencil(int s);
extern "C" void __cdecl glClientActiveTexture(unsigned texture);
extern "C" void __cdecl glClipPlanef(unsigned plane, PGLfloat equation);
extern "C" void __cdecl glClipPlanex(unsigned plane, PGLfixed equation);
extern "C" void __cdecl glColor4f(float red, float green, float blue, float alpha);
extern "C" void __cdecl glColor4ub(System::Byte red, System::Byte green, System::Byte blue, System::Byte alpha);
extern "C" void __cdecl glColor4x(int red, int green, int blue, int alpha);
extern "C" void __cdecl glColorMask(System::Byte red, System::Byte green, System::Byte blue, System::Byte alpha);
extern "C" void __cdecl glColorPointer(int size, unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glCompileShader(unsigned shader);
extern "C" void __cdecl glCompressedTexImage2D(unsigned target, int level, unsigned internalformat, int width, int height, int border, int imageSize, void * data);
extern "C" void __cdecl glCompressedTexSubImage2D(unsigned target, int level, int xoffset, int yoffset, int width, int height, unsigned format, int imageSize, void * data);
extern "C" void __cdecl glCopyTexImage2D(unsigned target, int level, unsigned internalformat, int x, int y, int width, int height, int border);
extern "C" void __cdecl glCopyTexSubImage2D(unsigned target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
extern "C" unsigned __cdecl glCreateProgram(void);
extern "C" unsigned __cdecl glCreateShader(unsigned type_);
extern "C" unsigned __cdecl glCreateShaderProgramvEXT(unsigned type_, int count, char * strings);
extern "C" void __cdecl glCullFace(unsigned mode);
extern "C" void __cdecl glCurrentPaletteMatrixOES(unsigned matrixpaletteindex);
extern "C" void __cdecl glDeleteBuffers(int n, PGLuint buffers);
extern "C" void __cdecl glDeleteFramebuffers(int n, PGLuint framebuffers);
extern "C" void __cdecl glDeleteFramebuffersOES(int n, PGLuint framebuffers);
extern "C" void __cdecl glDeleteProgram(unsigned program_);
extern "C" void __cdecl glDeleteProgramPipelinesEXT(int n, PGLuint pipelines);
extern "C" void __cdecl glDeleteQueriesEXT(int n, PGLuint ids);
extern "C" void __cdecl glDeleteRenderbuffers(int n, PGLuint renderbuffers);
extern "C" void __cdecl glDeleteRenderbuffersOES(int n, PGLuint renderbuffers);
extern "C" void __cdecl glDeleteShader(unsigned shader);
extern "C" void __cdecl glDeleteTextures(int n, PGLuint textures);
extern "C" void __cdecl glDeleteVertexArraysOES(int n, PGLuint arrays);
extern "C" void __cdecl glDepthFunc(unsigned func);
extern "C" void __cdecl glDepthMask(System::Byte flag);
extern "C" void __cdecl glDepthRangef(float zNear, float zFar);
extern "C" void __cdecl glDepthRangex(int zNear, int zFar);
extern "C" void __cdecl glDetachShader(unsigned program_, unsigned shader);
extern "C" void __cdecl glDisable(unsigned cap);
extern "C" void __cdecl glDisableClientState(unsigned array_);
extern "C" void __cdecl glDisableVertexAttribArray(unsigned index);
extern "C" void __cdecl glDiscardFramebufferEXT(unsigned target, int numAttachments, PGLenum attachments);
extern "C" void __cdecl glDrawArrays(unsigned mode, int first, int count);
extern "C" void __cdecl glDrawElements(unsigned mode, int count, unsigned type_, void * indices);
extern "C" void __cdecl glDrawTexfOES(float x, float y, float z, float width, float height);
extern "C" void __cdecl glDrawTexfvOES(PGLfloat coords);
extern "C" void __cdecl glDrawTexiOES(int x, int y, int z, int width, int height);
extern "C" void __cdecl glDrawTexivOES(PGLint coords);
extern "C" void __cdecl glDrawTexsOES(short x, short y, short z, short width, short height);
extern "C" void __cdecl glDrawTexsvOES(PGLshort coords);
extern "C" void __cdecl glDrawTexxOES(int x, int y, int z, int width, int height);
extern "C" void __cdecl glDrawTexxvOES(PGLfixed coords);
extern "C" void __cdecl glEnable(unsigned cap);
extern "C" void __cdecl glEnableClientState(unsigned array_);
extern "C" void __cdecl glEnableVertexAttribArray(unsigned index);
extern "C" void __cdecl glEndQueryEXT(unsigned target);
extern "C" void __cdecl glFinish(void);
extern "C" void __cdecl glFlush(void);
extern "C" void __cdecl glFogf(unsigned pname, float param);
extern "C" void __cdecl glFogfv(unsigned pname, PGLfloat params);
extern "C" void __cdecl glFogx(unsigned pname, int param);
extern "C" void __cdecl glFogxv(unsigned pname, PGLfixed params);
extern "C" void __cdecl glFramebufferRenderbuffer(unsigned target, unsigned attachment, unsigned renderbuffertarget, unsigned renderbuffer);
extern "C" void __cdecl glFramebufferRenderbufferOES(unsigned target, unsigned attachment, unsigned renderbuffertarget, unsigned renderbuffer);
extern "C" void __cdecl glFramebufferTexture2D(unsigned target, unsigned attachment, unsigned textarget, unsigned texture, int level);
extern "C" void __cdecl glFramebufferTexture2DOES(unsigned target, unsigned attachment, unsigned textarget, unsigned texture, int level);
extern "C" void __cdecl glFrontFace(unsigned mode);
extern "C" void __cdecl glFrustumf(float left, float right, float bottom, float top, float zNear, float zFar);
extern "C" void __cdecl glFrustumx(int left, int right, int bottom, int top, int zNear, int zFar);
extern "C" void __cdecl glGenBuffers(int n, PGLuint buffers);
extern "C" void __cdecl glGenFramebuffers(int n, PGLuint framebuffers);
extern "C" void __cdecl glGenFramebuffersOES(int n, PGLuint framebuffers);
extern "C" void __cdecl glGenProgramPipelinesEXT(int n, PGLuint pipelines);
extern "C" void __cdecl glGenQueriesEXT(int n, PGLuint ids);
extern "C" void __cdecl glGenRenderbuffers(int n, PGLuint renderbuffers);
extern "C" void __cdecl glGenRenderbuffersOES(int n, PGLuint renderbuffers);
extern "C" void __cdecl glGenTextures(int n, PGLuint textures);
extern "C" void __cdecl glGenVertexArraysOES(int n, PGLuint arrays);
extern "C" void __cdecl glGenerateMipmap(unsigned target);
extern "C" void __cdecl glGenerateMipmapOES(unsigned target);
extern "C" void __cdecl glGetActiveAttrib(unsigned program_, unsigned index, int bufsize, PGLsizei length, PGLint size, PGLenum type_, char * name);
extern "C" void __cdecl glGetActiveUniform(unsigned program_, unsigned index, int bufsize, PGLsizei length, PGLint size, PGLenum type_, char * name);
extern "C" void __cdecl glGetAttachedShaders(unsigned program_, int maxcount, PGLsizei count, PGLuint shaders);
extern "C" int __cdecl glGetAttribLocation(unsigned program_, char * name);
extern "C" void __cdecl glGetBooleanv(unsigned pname, PGLboolean params);
extern "C" void __cdecl glGetBufferParameteriv(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glGetBufferPointervOES(unsigned target, unsigned pname, void * params);
extern "C" void __cdecl glGetClipPlanef(unsigned pname, PGLfloat equation);
extern "C" void __cdecl glGetClipPlanex(unsigned pname, PGLfixed eqn);
extern "C" unsigned __cdecl glGetError(void);
extern "C" void __cdecl glGetFixedv(unsigned pname, PGLfixed params);
extern "C" void __cdecl glGetFloatv(unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetFramebufferAttachmentParameteriv(unsigned target, unsigned attachment, unsigned pname, PGLint params);
extern "C" void __cdecl glGetFramebufferAttachmentParameterivOES(unsigned target, unsigned attachment, unsigned pname, PGLint params);
extern "C" void __cdecl glGetIntegerv(unsigned pname, PGLint params);
extern "C" void __cdecl glGetLightfv(unsigned light, unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetLightxv(unsigned light, unsigned pname, PGLfixed params);
extern "C" void __cdecl glGetMaterialfv(unsigned face, unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetMaterialxv(unsigned face, unsigned pname, PGLfixed params);
extern "C" void __cdecl glGetObjectLabelEXT(unsigned type_, unsigned object_, int bufSize, PGLsizei length, char * label_);
extern "C" void __cdecl glGetPointerv(unsigned pname, void * params);
extern "C" void __cdecl glGetProgramInfoLog(unsigned program_, int bufsize, PGLsizei length, char * infolog);
extern "C" void __cdecl glGetProgramPipelineInfoLogEXT(unsigned pipeline, int bufSize, PGLsizei length, char * infoLog);
extern "C" void __cdecl glGetProgramPipelineivEXT(unsigned pipeline, unsigned pname, PGLint params);
extern "C" void __cdecl glGetProgramiv(unsigned program_, unsigned pname, PGLint params);
extern "C" void __cdecl glGetQueryObjectivEXT(unsigned id, unsigned pname, PGLint params);
extern "C" void __cdecl glGetQueryObjectuivEXT(unsigned id, unsigned pname, PGLuint params);
extern "C" void __cdecl glGetQueryivEXT(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glGetRenderbufferParameteriv(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glGetRenderbufferParameterivOES(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glGetShaderInfoLog(unsigned shader, int bufsize, PGLsizei length, char * infolog);
extern "C" void __cdecl glGetShaderPrecisionFormat(unsigned shadertype, unsigned precisiontype, PGLint range, PGLint precision);
extern "C" void __cdecl glGetShaderSource(unsigned shader, int bufsize, PGLsizei length, char * source);
extern "C" void __cdecl glGetShaderiv(unsigned shader, unsigned pname, PGLint params);
extern "C" PGLubyte __cdecl glGetString(unsigned name);
extern "C" void __cdecl glGetTexEnvfv(unsigned env, unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetTexEnviv(unsigned env, unsigned pname, PGLint params);
extern "C" void __cdecl glGetTexEnvxv(unsigned env, unsigned pname, PGLfixed params);
extern "C" void __cdecl glGetTexParameterfv(unsigned target, unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetTexParameteriv(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glGetTexParameterxv(unsigned target, unsigned pname, PGLfixed params);
extern "C" int __cdecl glGetUniformLocation(unsigned program_, char * name);
extern "C" void __cdecl glGetUniformfv(unsigned program_, int location, PGLfloat params);
extern "C" void __cdecl glGetUniformiv(unsigned program_, int location, PGLint params);
extern "C" void __cdecl glGetVertexAttribPointerv(unsigned index, unsigned pname, void * pointer);
extern "C" void __cdecl glGetVertexAttribfv(unsigned index, unsigned pname, PGLfloat params);
extern "C" void __cdecl glGetVertexAttribiv(unsigned index, unsigned pname, PGLint params);
extern "C" void __cdecl glHint(unsigned target, unsigned mode);
extern "C" void __cdecl glInsertEventMarkerEXT(int length, char * marker);
extern "C" System::Byte __cdecl glIsBuffer(unsigned buffer);
extern "C" System::Byte __cdecl glIsEnabled(unsigned cap);
extern "C" System::Byte __cdecl glIsFramebuffer(unsigned framebuffer);
extern "C" System::Byte __cdecl glIsFramebufferOES(unsigned framebuffer);
extern "C" System::Byte __cdecl glIsProgram(unsigned program_);
extern "C" System::Byte __cdecl glIsProgramPipelineEXT(unsigned pipeline);
extern "C" System::Byte __cdecl glIsQueryEXT(unsigned id);
extern "C" System::Byte __cdecl glIsRenderbuffer(unsigned renderbuffer);
extern "C" System::Byte __cdecl glIsRenderbufferOES(unsigned renderbuffer);
extern "C" System::Byte __cdecl glIsShader(unsigned shader);
extern "C" System::Byte __cdecl glIsTexture(unsigned texture);
extern "C" System::Byte __cdecl glIsVertexArrayOES(unsigned array_);
extern "C" void __cdecl glLabelObjectEXT(unsigned type_, unsigned object_, int length, char * label_);
extern "C" void __cdecl glLightModelf(unsigned pname, float param);
extern "C" void __cdecl glLightModelfv(unsigned pname, PGLfloat params);
extern "C" void __cdecl glLightModelx(unsigned pname, int param);
extern "C" void __cdecl glLightModelxv(unsigned pname, PGLfixed params);
extern "C" void __cdecl glLightf(unsigned light, unsigned pname, float param);
extern "C" void __cdecl glLightfv(unsigned light, unsigned pname, PGLfloat params);
extern "C" void __cdecl glLightx(unsigned light, unsigned pname, int param);
extern "C" void __cdecl glLightxv(unsigned light, unsigned pname, PGLfixed params);
extern "C" void __cdecl glLineWidth(float width);
extern "C" void __cdecl glLineWidthx(int width);
extern "C" void __cdecl glLinkProgram(unsigned program_);
extern "C" void __cdecl glLoadIdentity(void);
extern "C" void __cdecl glLoadMatrixf(PGLfloat m);
extern "C" void __cdecl glLoadMatrixx(PGLfixed m);
extern "C" void __cdecl glLoadPaletteFromModelViewMatrixOES(void);
extern "C" void __cdecl glLogicOp(unsigned opcode);
extern "C" void * __cdecl glMapBufferOES(unsigned target, unsigned access);
extern "C" void __cdecl glMaterialf(unsigned face, unsigned pname, float param);
extern "C" void __cdecl glMaterialfv(unsigned face, unsigned pname, PGLfloat params);
extern "C" void __cdecl glMaterialx(unsigned face, unsigned pname, int param);
extern "C" void __cdecl glMaterialxv(unsigned face, unsigned pname, PGLfixed params);
extern "C" void __cdecl glMatrixIndexPointerOES(int size, unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glMatrixMode(unsigned mode);
extern "C" void __cdecl glMultMatrixf(PGLfloat m);
extern "C" void __cdecl glMultMatrixx(PGLfixed m);
extern "C" void __cdecl glMultiTexCoord4f(unsigned target, float s, float t, float r, float q);
extern "C" void __cdecl glMultiTexCoord4x(unsigned target, int s, int t, int r, int q);
extern "C" void __cdecl glNormal3f(float nx, float ny, float nz);
extern "C" void __cdecl glNormal3x(int nx, int ny, int nz);
extern "C" void __cdecl glNormalPointer(unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glOrthof(float left, float right, float bottom, float top, float zNear, float zFar);
extern "C" void __cdecl glOrthox(int left, int right, int bottom, int top, int zNear, int zFar);
extern "C" void __cdecl glPixelStorei(unsigned pname, int param);
extern "C" void __cdecl glPointParameterf(unsigned pname, float param);
extern "C" void __cdecl glPointParameterfv(unsigned pname, PGLfloat params);
extern "C" void __cdecl glPointParameterx(unsigned pname, int param);
extern "C" void __cdecl glPointParameterxv(unsigned pname, PGLfixed params);
extern "C" void __cdecl glPointSize(float size);
extern "C" void __cdecl glPointSizePointerOES(unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glPointSizex(int size);
extern "C" void __cdecl glPolygonOffset(float factor, float units);
extern "C" void __cdecl glPolygonOffsetx(int factor, int units);
extern "C" void __cdecl glPopGroupMarkerEXT(void);
extern "C" void __cdecl glPopMatrix(void);
extern "C" void __cdecl glProgramParameteriEXT(unsigned program_, unsigned pname, int value);
extern "C" void __cdecl glProgramUniform1fEXT(unsigned program_, int location, float x);
extern "C" void __cdecl glProgramUniform1fvEXT(unsigned program_, int location, int count, PGLfloat value);
extern "C" void __cdecl glProgramUniform1iEXT(unsigned program_, int location, int x);
extern "C" void __cdecl glProgramUniform1ivEXT(unsigned program_, int location, int count, PGLint value);
extern "C" void __cdecl glProgramUniform2fEXT(unsigned program_, int location, float x, float y);
extern "C" void __cdecl glProgramUniform2fvEXT(unsigned program_, int location, int count, PGLfloat value);
extern "C" void __cdecl glProgramUniform2iEXT(unsigned program_, int location, int x, int y);
extern "C" void __cdecl glProgramUniform2ivEXT(unsigned program_, int location, int count, PGLint value);
extern "C" void __cdecl glProgramUniform3fEXT(unsigned program_, int location, float x, float y, float z);
extern "C" void __cdecl glProgramUniform3fvEXT(unsigned program_, int location, int count, PGLfloat value);
extern "C" void __cdecl glProgramUniform3iEXT(unsigned program_, int location, int x, int y, int z);
extern "C" void __cdecl glProgramUniform3ivEXT(unsigned program_, int location, int count, PGLint value);
extern "C" void __cdecl glProgramUniform4fEXT(unsigned program_, int location, float x, float y, float z, float w);
extern "C" void __cdecl glProgramUniform4fvEXT(unsigned program_, int location, int count, PGLfloat value);
extern "C" void __cdecl glProgramUniform4iEXT(unsigned program_, int location, int x, int y, int z, int w);
extern "C" void __cdecl glProgramUniform4ivEXT(unsigned program_, int location, int count, PGLint value);
extern "C" void __cdecl glProgramUniformMatrix2fvEXT(unsigned program_, int location, int count, System::Byte transpose, PGLfloat value);
extern "C" void __cdecl glProgramUniformMatrix3fvEXT(unsigned program_, int location, int count, System::Byte transpose, PGLfloat value);
extern "C" void __cdecl glProgramUniformMatrix4fvEXT(unsigned program_, int location, int count, System::Byte transpose, PGLfloat value);
extern "C" void __cdecl glPushGroupMarkerEXT(int length, char * marker);
extern "C" void __cdecl glPushMatrix(void);
extern "C" void __cdecl glReadPixels(int x, int y, int width, int height, unsigned format, unsigned type_, void * pixels);
extern "C" void __cdecl glReleaseShaderCompiler(void);
extern "C" void __cdecl glRenderbufferStorage(unsigned target, unsigned internalformat, int width, int height);
extern "C" void __cdecl glRenderbufferStorageMultisampleAPPLE(unsigned target, int samples, unsigned internalformat, int width, int height);
extern "C" void __cdecl glRenderbufferStorageOES(unsigned target, unsigned internalformat, int width, int height);
extern "C" void __cdecl glResolveMultisampleFramebufferAPPLE(void);
extern "C" void __cdecl glRotatef(float angle, float x, float y, float z);
extern "C" void __cdecl glRotatex(int angle, int x, int y, int z);
extern "C" void __cdecl glSampleCoverage(float value, System::Byte invert);
extern "C" void __cdecl glSampleCoveragex(int value, System::Byte invert);
extern "C" void __cdecl glScalef(float x, float y, float z);
extern "C" void __cdecl glScalex(int x, int y, int z);
extern "C" void __cdecl glScissor(int x, int y, int width, int height);
extern "C" void __cdecl glShadeModel(unsigned mode);
extern "C" void __cdecl glShaderBinary(int n, PGLuint shaders, unsigned binaryformat, void * binary, int length);
extern "C" void __cdecl glShaderSource(unsigned shader, int count, char * string_, PGLint length);
extern "C" void __cdecl glStencilFunc(unsigned func, int ref, unsigned mask);
extern "C" void __cdecl glStencilFuncSeparate(unsigned face, unsigned func, int ref, unsigned mask);
extern "C" void __cdecl glStencilMask(unsigned mask);
extern "C" void __cdecl glStencilMaskSeparate(unsigned face, unsigned mask);
extern "C" void __cdecl glStencilOp(unsigned fail, unsigned zfail, unsigned zpass);
extern "C" void __cdecl glStencilOpSeparate(unsigned face, unsigned fail, unsigned zfail, unsigned zpass);
extern "C" void __cdecl glTexCoordPointer(int size, unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glTexEnvf(unsigned target, unsigned pname, float param);
extern "C" void __cdecl glTexEnvfv(unsigned target, unsigned pname, PGLfloat params);
extern "C" void __cdecl glTexEnvi(unsigned target, unsigned pname, int param);
extern "C" void __cdecl glTexEnviv(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glTexEnvx(unsigned target, unsigned pname, int param);
extern "C" void __cdecl glTexEnvxv(unsigned target, unsigned pname, PGLfixed params);
extern "C" void __cdecl glTexImage2D(unsigned target, int level, int internalformat, int width, int height, int border, unsigned format, unsigned type_, void * pixels);
extern "C" void __cdecl glTexParameterf(unsigned target, unsigned pname, float param);
extern "C" void __cdecl glTexParameterfv(unsigned target, unsigned pname, PGLfloat params);
extern "C" void __cdecl glTexParameteri(unsigned target, unsigned pname, int param);
extern "C" void __cdecl glTexParameteriv(unsigned target, unsigned pname, PGLint params);
extern "C" void __cdecl glTexParameterx(unsigned target, unsigned pname, int param);
extern "C" void __cdecl glTexParameterxv(unsigned target, unsigned pname, PGLfixed params);
extern "C" void __cdecl glTexSubImage2D(unsigned target, int level, int xoffset, int yoffset, int width, int height, unsigned format, unsigned type_, void * pixels);
extern "C" void __cdecl glTranslatef(float x, float y, float z);
extern "C" void __cdecl glTranslatex(int x, int y, int z);
extern "C" void __cdecl glUniform1f(int location, float x);
extern "C" void __cdecl glUniform1fv(int location, int count, PGLfloat v);
extern "C" void __cdecl glUniform1i(int location, int x);
extern "C" void __cdecl glUniform1iv(int location, int count, PGLint v);
extern "C" void __cdecl glUniform2f(int location, float x, float y);
extern "C" void __cdecl glUniform2fv(int location, int count, PGLfloat v);
extern "C" void __cdecl glUniform2i(int location, int x, int y);
extern "C" void __cdecl glUniform2iv(int location, int count, PGLint v);
extern "C" void __cdecl glUniform3f(int location, float x, float y, float z);
extern "C" void __cdecl glUniform3fv(int location, int count, PGLfloat v);
extern "C" void __cdecl glUniform3i(int location, int x, int y, int z);
extern "C" void __cdecl glUniform3iv(int location, int count, PGLint v);
extern "C" void __cdecl glUniform4f(int location, float x, float y, float z, float w);
extern "C" void __cdecl glUniform4fv(int location, int count, PGLfloat v);
extern "C" void __cdecl glUniform4i(int location, int x, int y, int z, int w);
extern "C" void __cdecl glUniform4iv(int location, int count, PGLint v);
extern "C" void __cdecl glUniformMatrix2fv(int location, int count, System::Byte transpose, PGLfloat value);
extern "C" void __cdecl glUniformMatrix3fv(int location, int count, System::Byte transpose, PGLfloat value);
extern "C" void __cdecl glUniformMatrix4fv(int location, int count, System::Byte transpose, PGLfloat value);
extern "C" System::Byte __cdecl glUnmapBufferOES(unsigned target);
extern "C" void __cdecl glUseProgram(unsigned program_);
extern "C" void __cdecl glUseProgramStagesEXT(unsigned pipeline, unsigned stages, unsigned program_);
extern "C" void __cdecl glValidateProgram(unsigned program_);
extern "C" void __cdecl glValidateProgramPipelineEXT(unsigned pipeline);
extern "C" void __cdecl glVertexAttrib1f(unsigned indx, float x);
extern "C" void __cdecl glVertexAttrib1fv(unsigned indx, PGLfloat values);
extern "C" void __cdecl glVertexAttrib2f(unsigned indx, float x, float y);
extern "C" void __cdecl glVertexAttrib2fv(unsigned indx, PGLfloat values);
extern "C" void __cdecl glVertexAttrib3f(unsigned indx, float x, float y, float z);
extern "C" void __cdecl glVertexAttrib3fv(unsigned indx, PGLfloat values);
extern "C" void __cdecl glVertexAttrib4f(unsigned indx, float x, float y, float z, float w);
extern "C" void __cdecl glVertexAttrib4fv(unsigned indx, PGLfloat values);
extern "C" void __cdecl glVertexAttribPointer(unsigned indx, int size, unsigned type_, System::Byte normalized, int stride, void * ptr);
extern "C" void __cdecl glVertexPointer(int size, unsigned type_, int stride, void * pointer);
extern "C" void __cdecl glViewport(int x, int y, int width, int height);
extern "C" void __cdecl glWeightPointerOES(int size, unsigned type_, int stride, void * pointer);
}	/* namespace Opengles */
}	/* namespace Iosapi */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_IOSAPI_OPENGLES)
using namespace Iosapi::Opengles;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_IOSAPI)
using namespace Iosapi;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Iosapi_OpenglesHPP
