// CodeGear C++Builder
// Copyright (c) 1995, 2021 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'REST.BindSource.pas' rev: 34.00 (iOS)

#ifndef Rest_BindsourceHPP
#define Rest_BindsourceHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <System.SysUtils.hpp>
#include <System.Classes.hpp>
#include <System.TypInfo.hpp>
#include <System.Generics.Collections.hpp>
#include <Data.Bind.Components.hpp>
#include <Data.Bind.ObjectScope.hpp>
#include <System.Rtti.hpp>
#include <System.Generics.Defaults.hpp>
#include <System.Types.hpp>

//-- user supplied -----------------------------------------------------------

namespace Rest
{
namespace Bindsource
{
//-- forward type declarations -----------------------------------------------
class DELPHICLASS TRESTComponentNotify;
class DELPHICLASS TRESTJSONComponentNotify;
class DELPHICLASS TRESTComponentAdapter;
class DELPHICLASS TRESTComponentBindSource;
template<typename T> class DELPHICLASS TRESTComponentNotifyList__1;
//-- type declarations -------------------------------------------------------
class PASCALIMPLEMENTATION TRESTComponentNotify : public System::TObject
{
	typedef System::TObject inherited;
	
public:
	virtual void __fastcall PropertyValueChanged(System::TObject* Sender);
public:
	/* TObject.Create */ inline __fastcall TRESTComponentNotify() : System::TObject() { }
	/* TObject.Destroy */ inline __fastcall virtual ~TRESTComponentNotify() { }
	
};


class PASCALIMPLEMENTATION TRESTJSONComponentNotify : public TRESTComponentNotify
{
	typedef TRESTComponentNotify inherited;
	
public:
	virtual void __fastcall JSONValueChanged(System::TObject* Sender);
public:
	/* TObject.Create */ inline __fastcall TRESTJSONComponentNotify() : TRESTComponentNotify() { }
	/* TObject.Destroy */ inline __fastcall virtual ~TRESTJSONComponentNotify() { }
	
};


class PASCALIMPLEMENTATION TRESTComponentAdapter : public Data::Bind::Objectscope::TBindSourceAdapter
{
	typedef Data::Bind::Objectscope::TBindSourceAdapter inherited;
	
	
public:
	class DELPHICLASS TNotify;
	class PASCALIMPLEMENTATION TNotify : public TRESTComponentNotify
	{
		typedef TRESTComponentNotify inherited;
		
	private:
		TRESTComponentAdapter* FAdapter;
		
	public:
		__fastcall TNotify(TRESTComponentAdapter* const AAdapter);
		virtual void __fastcall PropertyValueChanged(System::TObject* Sender);
	public:
		/* TObject.Destroy */ inline __fastcall virtual ~TNotify() { }
		
	};
	
	
	template<typename T> class DELPHICLASS TReadWriteField__1;
	// Template declaration generated by Delphi parameterized types is
	// used only for accessing Delphi variables and fields.
	// Don't instantiate with new type parameters in user code.
	template<typename T> class PASCALIMPLEMENTATION TReadWriteField__1 : public Data::Bind::Objectscope::TBindSourceAdapterReadWriteField__1<T>
	{
		typedef Data::Bind::Objectscope::TBindSourceAdapterReadWriteField__1<T> inherited;
		
	private:
		System::Classes::TPersistent* FPersistent;
		
	public:
		__property System::Classes::TPersistent* Persistent = {read=FPersistent};
	public:
		/* {Data_Bind_ObjectScope}TBindSourceAdapterReadWriteField<REST_BindSource_TReadWriteField<T>_T>.Create */ inline __fastcall TReadWriteField__1(Data::Bind::Objectscope::TBindSourceAdapter* AOwner, const System::UnicodeString AMemberName, const Data::Bind::Objectscope::TBindSourceAdapterFieldType &AType, const Data::Bind::Objectscope::_di_IGetMemberObject AGetMemberObject, Data::Bind::Objectscope::TValueReader__1<T>* const AReader, Data::Bind::Objectscope::TValueWriter__1<T>* const AWriter, Data::Bind::Components::TScopeMemberType AMemberType) : Data::Bind::Objectscope::TBindSourceAdapterReadWriteField__1<T>(AOwner, AMemberName, AType, AGetMemberObject, AReader, AWriter, AMemberType) { }
		/* {Data_Bind_ObjectScope}TBindSourceAdapterReadWriteField<REST_BindSource_TReadWriteField<T>_T>.Destroy */ inline __fastcall virtual ~TReadWriteField__1() { }
		
	};
	
	
	template<typename T> class DELPHICLASS TReadField__1;
	// Template declaration generated by Delphi parameterized types is
	// used only for accessing Delphi variables and fields.
	// Don't instantiate with new type parameters in user code.
	template<typename T> class PASCALIMPLEMENTATION TReadField__1 : public Data::Bind::Objectscope::TBindSourceAdapterReadField__1<T>
	{
		typedef Data::Bind::Objectscope::TBindSourceAdapterReadField__1<T> inherited;
		
	private:
		System::Classes::TPersistent* FPersistent;
		
	public:
		__property System::Classes::TPersistent* Persistent = {read=FPersistent};
	public:
		/* {Data_Bind_ObjectScope}TBindSourceAdapterReadField<REST_BindSource_TReadField<T>_T>.Create */ inline __fastcall TReadField__1(Data::Bind::Objectscope::TBindSourceAdapter* AOwner, const System::UnicodeString AMemberName, const Data::Bind::Objectscope::TBindSourceAdapterFieldType &AType, const Data::Bind::Objectscope::_di_IGetMemberObject AGetMemberObject, Data::Bind::Objectscope::TValueReader__1<T>* const AReader, Data::Bind::Components::TScopeMemberType AMemberType) : Data::Bind::Objectscope::TBindSourceAdapterReadField__1<T>(AOwner, AMemberName, AType, AGetMemberObject, AReader, AMemberType) { }
		/* {Data_Bind_ObjectScope}TBindSourceAdapterReadField<REST_BindSource_TReadField<T>_T>.Destroy */ inline __fastcall virtual ~TReadField__1() { }
		
	};
	
	
	
private:
	bool FDeferActivate;
	bool FPosting;
	bool __fastcall HasComponent();
	bool __fastcall ComponentLoading();
	
protected:
	virtual void __fastcall DoChangePosting();
	virtual void __fastcall DoAfterPostFields(System::TArray__1<Data::Bind::Objectscope::TBindSourceAdapterField*> AFields);
	virtual void __fastcall DoBeforePostFields(System::TArray__1<Data::Bind::Objectscope::TBindSourceAdapterField*> AFields);
	virtual Data::Bind::Components::TBaseLinkingBindSource* __fastcall GetSource();
	virtual void __fastcall Loaded();
	virtual void __fastcall SetActive(bool AValue);
	virtual bool __fastcall GetCanActivate();
	virtual bool __fastcall GetCanModify();
	virtual bool __fastcall SupportsNestedFields();
	virtual int __fastcall GetCount();
	virtual void __fastcall DoBeforeOpen();
	virtual void __fastcall DoAfterClose();
	virtual void __fastcall AddFields();
	void __fastcall CheckInactive();
	template<typename T> void __fastcall CreateReadOnlyField(const System::UnicodeString AFieldName, const Data::Bind::Objectscope::_di_IGetMemberObject AGetMemberObject, Data::Bind::Components::TScopeMemberType AMemberType, const System::DelphiInterface<System::Sysutils::TFunc__1<T> > AGetterFunc, System::Classes::TPersistent* const APersistent = (System::Classes::TPersistent*)(0x0));
	template<typename T> void __fastcall CreateReadWriteField(const System::UnicodeString AFieldName, const Data::Bind::Objectscope::_di_IGetMemberObject AGetMemberObject, Data::Bind::Components::TScopeMemberType AMemberType, const System::DelphiInterface<System::Sysutils::TFunc__1<T> > AGetterFunc, const System::DelphiInterface<System::Sysutils::TProc__1<T> > ASetterProc, System::Classes::TPersistent* const APersistent = (System::Classes::TPersistent*)(0x0));
	void __fastcall RefreshFields();
	__property bool Posting = {read=FPosting, nodefault};
public:
	/* TBindSourceAdapter.Create */ inline __fastcall virtual TRESTComponentAdapter(System::Classes::TComponent* AOwner) : Data::Bind::Objectscope::TBindSourceAdapter(AOwner) { }
	/* TBindSourceAdapter.Destroy */ inline __fastcall virtual ~TRESTComponentAdapter() { }
	
};


class PASCALIMPLEMENTATION TRESTComponentBindSource : public Data::Bind::Objectscope::TBaseObjectBindSource
{
	typedef Data::Bind::Objectscope::TBaseObjectBindSource inherited;
	
private:
	TRESTComponentAdapter* FAdapter;
	
private:
	bool __fastcall GetAutoEdit();
	bool __fastcall GetAutoPost();
	void __fastcall SetAutoEdit(const bool AValue);
	void __fastcall SetAutoPost(const bool AValue);
	
protected:
	virtual Data::Bind::Objectscope::TBindSourceAdapter* __fastcall GetInternalAdapter();
	virtual TRESTComponentAdapter* __fastcall CreateAdapter() = 0 ;
	
public:
	__fastcall virtual TRESTComponentBindSource(System::Classes::TComponent* AOwner);
	__property bool AutoEdit = {read=GetAutoEdit, write=SetAutoEdit, default=1};
	__property bool AutoPost = {read=GetAutoPost, write=SetAutoPost, default=1};
	__property AutoActivate = {default=1};
	__property TRESTComponentAdapter* Adapter = {read=FAdapter};
public:
	/* TBaseObjectBindSource.Destroy */ inline __fastcall virtual ~TRESTComponentBindSource() { }
	
};


// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION TRESTComponentNotifyList__1 : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	System::Generics::Collections::TList__1<T>* FNotifyList;
	
public:
	__fastcall TRESTComponentNotifyList__1();
	__fastcall virtual ~TRESTComponentNotifyList__1();
	void __fastcall AddNotify(const T ANotify);
	void __fastcall RemoveNotify(const T ANotify);
	void __fastcall Notify(const System::DelphiInterface<System::Sysutils::TProc__1<T> > AProc);
};


//-- var, const, procedure ---------------------------------------------------
}	/* namespace Bindsource */
}	/* namespace Rest */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_REST_BINDSOURCE)
using namespace Rest::Bindsource;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_REST)
using namespace Rest;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Rest_BindsourceHPP
